import EverettianProbability.Refinement.PayoffPreserving

/-!
**FR.** # Témoin physique d'un raffinement record-neutre (P6a)

Un raffinement redécrit plus finement les branches sans en créer de
nouvelles au sens physique lorsqu'il existe une évolution unitaire concrète
qui (i) laisse inchangé tout record accessible, (ii) laisse inchangée toute
conséquence décisionnelle, (iii) laisse inchangés les poids borniens des
cellules de records, et (iv) augmente néanmoins le nombre de cellules
distinguées par la perspective fine. Ce fichier construit un tel témoin dans
`H 3`, avec des amplitudes inégales (`3/5`, `4/5`) : des amplitudes égales
rendraient le témoin inerte, la scission du second coefficient étant alors
invisible à toute règle symétrique.

Construction. Trois vecteurs orthonormés `b 0, b 1, b 2` de `H 3` : `b 0` est
l'étiquette de la branche macroscopique observée ; `b 1` et `b 2` forment un
ancilla à deux niveaux, initialisé dans l'état `b 1`. La perspective grossière
`coarsePerspective` distingue seulement `label0Line` et son complément
orthogonal `label1Space`. La perspective fine `finePerspective` est la
perspective de base engendrée par `b`, qui distingue en outre `anc0Line` et
`anc1Line` à l'intérieur de `label1Space`. L'unitaire `coupleU` fixe `b 0` et
fait tourner le bloc `{b 1, b 2}` par la matrice de rotation `(3/5, 4/5; 4/5,
-3/5)`, couplant ainsi l'ancilla à la branche `label0Line` sans jamais faire
sortir la population de `label1Space`.

L'hypothèse `RefinementNotInRecordAlgebra` est explicite et nommée, et son
nom décrit exactement ce que son type affirme : les deux cellules produites
par le raffinement (`anc0Line`, `anc1Line`) ne sont pas des cellules de
l'algèbre de records. C'est elle, et non un théorème physique, qui fait de
l'« ancilla » — au sens de la prose ci-dessus — un degré de liberté
inaccessible à l'agent : `H 3` ne porte aucune factorisation tensorielle
système/ancilla, et `coupleU` est, au niveau du type, une simple rotation
interne sur un bloc de deux vecteurs de base ; l'appeler « couplage
d'ancilla » est une interprétation physique de cette rotation, non un fait
porté par sa signature. Un lecteur qui refuse cette hypothèse — par exemple
parce qu'il tient `anc0Line`/`anc1Line` pour directement enregistrés —
rejette du même geste le statut de témoin *record-neutre* de ce
raffinement, sans remettre en cause aucun des calculs de poids bornien
ci-dessous.

**EN.** # Physical witness of a record-neutral refinement (P6a)

A refinement redescribes branches more finely without physically creating
new ones when there is a concrete unitary evolution that (i) leaves every
accessible record unchanged, (ii) leaves every decision-relevant consequence
unchanged, (iii) leaves the Born weights of the record cells unchanged, and
(iv) nonetheless increases the number of cells distinguished by the fine
perspective. This file builds such a witness in `H 3`, with unequal
amplitudes (`3/5`, `4/5`): equal amplitudes would make the witness inert,
since the splitting of the second coefficient would then be invisible to any
symmetric rule.

Construction. Three orthonormal vectors `b 0, b 1, b 2` of `H 3`: `b 0` is
the label of the observed macroscopic branch; `b 1` and `b 2` form a
two-level ancilla, initialized in state `b 1`. The coarse perspective
`coarsePerspective` distinguishes only `label0Line` and its orthogonal
complement `label1Space`. The fine perspective `finePerspective` is the
basis perspective generated by `b`, which additionally distinguishes
`anc0Line` and `anc1Line` inside `label1Space`. The unitary `coupleU` fixes
`b 0` and rotates the `{b 1, b 2}` block by the rotation matrix `(3/5, 4/5;
4/5, -3/5)`, thereby coupling the ancilla to the `label0Line` branch without
ever moving population out of `label1Space`.

The hypothesis `RefinementNotInRecordAlgebra` is explicit and named, and its
name describes exactly what its type states: the two cells produced by the
refinement (`anc0Line`, `anc1Line`) are not cells of the record algebra. It
is this hypothesis, not a physical theorem, that makes the "ancilla" — in
the sense of the prose above — an inaccessible degree of freedom for the
agent: `H 3` carries no system/ancilla tensor factorization, and at the
type level `coupleU` is simply an internal rotation on a block of two basis
vectors; calling it an "ancilla coupling" is a physical interpretation of
that rotation, not a fact carried by its signature. A reader who rejects
this hypothesis — for instance by treating `anc0Line`/`anc1Line` as
directly recorded — thereby rejects this refinement's *record-neutral*
status, without disputing any of the Born weight computations below.
-/

namespace EverettianProbability.PhysicalRefinement

open QuantumFoundations.ProbabilityAPI EverettianProbability.Core EverettianProbability.Refinement
open QuantumFoundations.Uhlhorn (projL_singleton_unit)
open scoped Classical InnerProductSpace

/-- The fixed orthonormal frame: `b 0` is the observed branch label, `b 1`
and `b 2` the two ancilla levels. -/
noncomputable def b : OrthonormalBasis (Fin 3) ℂ (H 3) := EuclideanSpace.basisFun (Fin 3) ℂ

theorem b0_unit : ‖(b 0 : H 3)‖ = 1 := b.orthonormal.1 0
theorem b1_unit : ‖(b 1 : H 3)‖ = 1 := b.orthonormal.1 1
theorem b2_unit : ‖(b 2 : H 3)‖ = 1 := b.orthonormal.1 2

/-- Line spanned by the observed branch label. -/
noncomputable def label0Line : Submodule ℂ (H 3) := ℂ ∙ (b 0 : H 3)

/-- Line spanned by the ancilla's initial level. -/
noncomputable def anc0Line : Submodule ℂ (H 3) := ℂ ∙ (b 1 : H 3)

/-- Line spanned by the ancilla's second level, populated only after
coupling. -/
noncomputable def anc1Line : Submodule ℂ (H 3) := ℂ ∙ (b 2 : H 3)

theorem label0Line_ne_bot : label0Line ≠ ⊥ := QuantumFoundations.BornRule.line_ne_bot b 0
theorem label0Line_ne_top : label0Line ≠ ⊤ :=
  QuantumFoundations.BornRule.line_ne_top (by norm_num) b 0

/-- Orthogonal complement of the observed branch label: the record cell
that hosts the ancilla, both before and after coupling. -/
noncomputable def label1Space : Submodule ℂ (H 3) := label0Lineᗮ

/-- Coarse, record-level perspective: only the observed branch and its
complement are distinguished. -/
noncomputable def coarsePerspective : Perspective 3 :=
  Perspective.binary label0Line label0Line_ne_bot label0Line_ne_top

/-- Fine perspective generated by the full frame `b`: distinguishes the two
ancilla levels inside `label1Space`. -/
noncomputable def finePerspective : Perspective 3 :=
  QuantumFoundations.BornRule.basisPerspective b

theorem anc0Line_le_label1Space : anc0Line ≤ label1Space := by
  unfold anc0Line label1Space
  rw [Submodule.span_singleton_le_iff_mem, Submodule.mem_orthogonal]
  intro u hu
  obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hu
  rw [inner_smul_left]
  have h : (⟪(b 0 : H 3), (b 1 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  rw [h, mul_zero]

theorem anc1Line_le_label1Space : anc1Line ≤ label1Space := by
  unfold anc1Line label1Space
  rw [Submodule.span_singleton_le_iff_mem, Submodule.mem_orthogonal]
  intro u hu
  obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hu
  rw [inner_smul_left]
  have h : (⟪(b 0 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  rw [h, mul_zero]

/-- **FR.** Le premier des quatre théorèmes obligatoires : la perspective
fine raffine bien la perspective grossière.

**EN.** The first of the four mandatory theorems: the fine perspective does
refine the coarse one. -/
theorem recordNeutral_refines : Refines finePerspective coarsePerspective := by
  intro c' hc'
  unfold finePerspective QuantumFoundations.BornRule.basisPerspective at hc'
  simp only [Finset.mem_image, Finset.mem_univ, true_and] at hc'
  obtain ⟨i, rfl⟩ := hc'
  show ∃ c ∈ coarsePerspective.cells, (ℂ ∙ (b i : H 3)) ≤ c
  fin_cases i
  · exact ⟨label0Line, Finset.mem_insert_self _ _, le_refl _⟩
  · exact ⟨label1Space, Finset.mem_insert_of_mem (Finset.mem_singleton_self _),
      anc0Line_le_label1Space⟩
  · exact ⟨label1Space, Finset.mem_insert_of_mem (Finset.mem_singleton_self _),
      anc1Line_le_label1Space⟩

theorem label0Line_mem_fine : label0Line ∈ finePerspective.cells := by
  unfold finePerspective QuantumFoundations.BornRule.basisPerspective label0Line
  simp only [Finset.mem_image, Finset.mem_univ, true_and]
  exact ⟨0, rfl⟩

theorem anc0Line_mem_fine : anc0Line ∈ finePerspective.cells := by
  unfold finePerspective QuantumFoundations.BornRule.basisPerspective anc0Line
  simp only [Finset.mem_image, Finset.mem_univ, true_and]
  exact ⟨1, rfl⟩

theorem anc1Line_mem_fine : anc1Line ∈ finePerspective.cells := by
  unfold finePerspective QuantumFoundations.BornRule.basisPerspective anc1Line
  simp only [Finset.mem_image, Finset.mem_univ, true_and]
  exact ⟨2, rfl⟩

theorem coarsePerspective_cells_eq : coarsePerspective.cells = {label0Line, label1Space} := rfl

theorem label0Line_ne_label1Space : label0Line ≠ label1Space := by
  intro h
  apply label0Line_ne_bot
  rw [Submodule.eq_bot_iff]
  intro x hx
  have hx' : x ∈ label1Space := h ▸ hx
  have hxorth : x ∈ label0Lineᗮ := hx'
  rw [Submodule.mem_orthogonal] at hxorth
  exact inner_self_eq_zero.mp (hxorth x hx)

theorem label1Space_mem_coarse : label1Space ∈ coarsePerspective.cells :=
  Finset.mem_insert_of_mem (Finset.mem_singleton_self _)

/- ================= the coupling unitary ================= -/

/-- Ancilla-coupling map: identity on `b 0`, rotation `(3/5, 4/5; 4/5,
-3/5)` on the `{b 1, b 2}` block. Proved isometric below, hence unitary on
the finite-dimensional `H 3`. -/
noncomputable def coupleU (x : H 3) : H 3 :=
  (b.repr x 0) • (b 0 : H 3)
    + ((3/5 : ℂ) * b.repr x 1 + (4/5 : ℂ) * b.repr x 2) • (b 1 : H 3)
    + ((4/5 : ℂ) * b.repr x 1 - (3/5 : ℂ) * b.repr x 2) • (b 2 : H 3)

theorem coupleU_add (x y : H 3) : coupleU (x + y) = coupleU x + coupleU y := by
  unfold coupleU; simp only [map_add, PiLp.add_apply]; module

theorem coupleU_smul (c : ℂ) (x : H 3) : coupleU (c • x) = c • coupleU x := by
  unfold coupleU; simp only [map_smul, PiLp.smul_apply, smul_eq_mul]; module

/-- Linear-map bundling of `coupleU`. -/
noncomputable def coupleULin : H 3 →ₗ[ℂ] H 3 where
  toFun := coupleU
  map_add' := coupleU_add
  map_smul' := coupleU_smul

theorem coupleU_inner_self (x : H 3) : (⟪coupleU x, coupleU x⟫_ℂ) = (⟪x, x⟫_ℂ) := by
  set x0 := b.repr x 0 with hx0
  set x1 := b.repr x 1 with hx1
  set x2 := b.repr x 2 with hx2
  have hxrepr : x = x0 • (b 0 : H 3) + x1 • (b 1 : H 3) + x2 • (b 2 : H 3) := by
    conv_lhs => rw [← b.sum_repr x]
    rw [Fin.sum_univ_three]
  have e0 : (⟪(b 0 : H 3), (b 1:H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  have e1 : (⟪(b 0 : H 3), (b 2:H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  have e2 : (⟪(b 1 : H 3), (b 2:H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  have e0' : (⟪(b 1 : H 3), (b 0:H 3)⟫_ℂ) = 0 := by rw [← inner_conj_symm, e0]; simp
  have e1' : (⟪(b 2 : H 3), (b 0:H 3)⟫_ℂ) = 0 := by rw [← inner_conj_symm, e1]; simp
  have e2' : (⟪(b 2 : H 3), (b 1:H 3)⟫_ℂ) = 0 := by rw [← inner_conj_symm, e2]; simp
  have n0 : (⟪(b 0 : H 3), (b 0:H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b0_unit]; norm_num
  have n1 : (⟪(b 1 : H 3), (b 1:H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b1_unit]; norm_num
  have n2 : (⟪(b 2 : H 3), (b 2:H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b2_unit]; norm_num
  have c35 : (starRingEnd ℂ) (3/5 : ℂ) = 3/5 := by simp [map_ofNat]
  have c45 : (starRingEnd ℂ) (4/5 : ℂ) = 4/5 := by simp [map_ofNat]
  conv_rhs => rw [hxrepr]
  unfold coupleU
  simp only [inner_add_left, inner_add_right, inner_smul_left, inner_smul_right,
    e0, e1, e2, e0', e1', e2', n0, n1, n2, mul_zero, mul_one, add_zero, zero_add,
    map_sub, map_add, map_mul, c35, c45]
  ring

/-- `coupleU` is an isometry, hence unitary on the finite-dimensional
`H 3`. -/
theorem coupleU_isometry (x : H 3) : ‖coupleU x‖ = ‖x‖ := by
  have h := coupleU_inner_self x
  rw [inner_self_eq_norm_sq_to_K (𝕜 := ℂ), inner_self_eq_norm_sq_to_K (𝕜 := ℂ)] at h
  have h2 : (‖coupleU x‖:ℝ)^2 = (‖x‖:ℝ)^2 := by exact_mod_cast h
  nlinarith [norm_nonneg (coupleU x), norm_nonneg x, h2]

/- ================= the witness states ================= -/

/-- State before coupling: unequal amplitudes `3/5` on the observed branch,
`4/5` on the ancilla's initial level, nothing on its second level. -/
noncomputable def psiBefore : H 3 := (3/5 : ℂ) • (b 0 : H 3) + (4/5 : ℂ) • (b 1 : H 3)

/-- State after coupling: `psiAfter = coupleU psiBefore`, computed
explicitly. -/
noncomputable def psiAfter : H 3 :=
  (3/5 : ℂ) • (b 0 : H 3) + (12/25 : ℂ) • (b 1 : H 3) + (16/25 : ℂ) • (b 2 : H 3)

theorem inner_b0_psiBefore : (⟪(b 0 : H 3), psiBefore⟫_ℂ) = 3/5 := by
  unfold psiBefore
  have h01 : (⟪(b 0 : H 3), (b 1 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  have h00 : (⟪(b 0 : H 3), (b 0 : H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b0_unit]; norm_num
  rw [inner_add_right, inner_smul_right, inner_smul_right, h01, h00]; ring

theorem inner_b1_psiBefore : (⟪(b 1 : H 3), psiBefore⟫_ℂ) = 4/5 := by
  unfold psiBefore
  have h10 : (⟪(b 1 : H 3), (b 0 : H 3)⟫_ℂ) = 0 := by
    have h01 : (⟪(b 0 : H 3), (b 1 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
    rw [← inner_conj_symm, h01]; simp
  have h11 : (⟪(b 1 : H 3), (b 1 : H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b1_unit]; norm_num
  rw [inner_add_right, inner_smul_right, inner_smul_right, h10, h11]; ring

theorem inner_b2_psiBefore : (⟪(b 2 : H 3), psiBefore⟫_ℂ) = 0 := by
  unfold psiBefore
  have h20 : (⟪(b 2 : H 3), (b 0 : H 3)⟫_ℂ) = 0 := by
    have h02 : (⟪(b 0 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
    rw [← inner_conj_symm, h02]; simp
  have h21 : (⟪(b 2 : H 3), (b 1 : H 3)⟫_ℂ) = 0 := by
    have h12 : (⟪(b 1 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
    rw [← inner_conj_symm, h12]; simp
  rw [inner_add_right, inner_smul_right, inner_smul_right, h20, h21]; ring

theorem inner_b0_psiAfter : (⟪(b 0 : H 3), psiAfter⟫_ℂ) = 3/5 := by
  unfold psiAfter
  have h01 : (⟪(b 0 : H 3), (b 1 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  have h02 : (⟪(b 0 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  have h00 : (⟪(b 0 : H 3), (b 0 : H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b0_unit]; norm_num
  rw [inner_add_right, inner_add_right, inner_smul_right, inner_smul_right, inner_smul_right,
    h01, h02, h00]; ring

theorem inner_b1_psiAfter : (⟪(b 1 : H 3), psiAfter⟫_ℂ) = 12/25 := by
  unfold psiAfter
  have h10 : (⟪(b 1 : H 3), (b 0 : H 3)⟫_ℂ) = 0 := by
    have h01 : (⟪(b 0 : H 3), (b 1 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
    rw [← inner_conj_symm, h01]; simp
  have h12 : (⟪(b 1 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  have h11 : (⟪(b 1 : H 3), (b 1 : H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b1_unit]; norm_num
  rw [inner_add_right, inner_add_right, inner_smul_right, inner_smul_right, inner_smul_right,
    h10, h12, h11]; ring

theorem inner_b2_psiAfter : (⟪(b 2 : H 3), psiAfter⟫_ℂ) = 16/25 := by
  unfold psiAfter
  have h20 : (⟪(b 2 : H 3), (b 0 : H 3)⟫_ℂ) = 0 := by
    have h02 : (⟪(b 0 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
    rw [← inner_conj_symm, h02]; simp
  have h21 : (⟪(b 2 : H 3), (b 1 : H 3)⟫_ℂ) = 0 := by
    have h12 : (⟪(b 1 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
    rw [← inner_conj_symm, h12]; simp
  have h22 : (⟪(b 2 : H 3), (b 2 : H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b2_unit]; norm_num
  rw [inner_add_right, inner_add_right, inner_smul_right, inner_smul_right, inner_smul_right,
    h20, h21, h22]; ring

/-- The state actually reached by the coupling unitary is exactly
`psiAfter`, computed in exact rational arithmetic. -/
theorem coupleU_psiBefore : coupleU psiBefore = psiAfter := by
  have h0 : b.repr psiBefore 0 = 3/5 := by unfold psiBefore; simp
  have h1 : b.repr psiBefore 1 = 4/5 := by unfold psiBefore; simp
  have h2 : b.repr psiBefore 2 = 0 := by unfold psiBefore; simp
  unfold coupleU psiAfter
  rw [h0, h1, h2]
  norm_num

theorem weight_label0_before : ‖projL label0Line psiBefore‖ ^ 2 = 9/25 := by
  unfold label0Line
  rw [projL_singleton_unit _ _ b0_unit, inner_b0_psiBefore, norm_smul, b0_unit, mul_one]
  norm_num

theorem weight_label0_after : ‖projL label0Line psiAfter‖ ^ 2 = 9/25 := by
  unfold label0Line
  rw [projL_singleton_unit _ _ b0_unit, inner_b0_psiAfter, norm_smul, b0_unit, mul_one]
  norm_num

theorem weight_anc0_before : ‖projL anc0Line psiBefore‖ ^ 2 = 16/25 := by
  unfold anc0Line
  rw [projL_singleton_unit _ _ b1_unit, inner_b1_psiBefore, norm_smul, b1_unit, mul_one]
  norm_num

theorem weight_anc1_before : ‖projL anc1Line psiBefore‖ ^ 2 = 0 := by
  unfold anc1Line
  rw [projL_singleton_unit _ _ b2_unit, inner_b2_psiBefore, norm_smul, b2_unit, mul_one]
  norm_num

theorem weight_anc0_after : ‖projL anc0Line psiAfter‖ ^ 2 = 144/625 := by
  unfold anc0Line
  rw [projL_singleton_unit _ _ b1_unit, inner_b1_psiAfter, norm_smul, b1_unit, mul_one]
  norm_num

theorem weight_anc1_after : ‖projL anc1Line psiAfter‖ ^ 2 = 256/625 := by
  unfold anc1Line
  rw [projL_singleton_unit _ _ b2_unit, inner_b2_psiAfter, norm_smul, b2_unit, mul_one]
  norm_num

/-- Generic Pythagorean split over the coarse (2-cell) perspective, for any
unit state `x`: `‖proj label0Line x‖² + ‖proj label1Space x‖² = 1`. -/
theorem coarse_weight_sum (x : H 3) (hx : ‖x‖ = 1) :
    ‖projL label0Line x‖ ^ 2 + ‖projL label1Space x‖ ^ 2 = 1 := by
  have hpyth := QuantumFoundations.BornRule.sum_sq_projL_of_pairwise_isOrtho
    coarsePerspective.cells coarsePerspective.ortho x
  have htop : coarsePerspective.cells.sup id = (⊤ : Submodule ℂ (H 3)) := by
    rw [Finset.sup_id_eq_sSup]; exact coarsePerspective.span
  have hid : projL (⊤ : Submodule ℂ (H 3)) = LinearMap.id := by
    unfold projL; rw [Submodule.starProjection_top]; rfl
  rw [htop, hid] at hpyth
  simp only [LinearMap.id_coe, id_eq, hx, one_pow] at hpyth
  rw [coarsePerspective_cells_eq,
    Finset.sum_insert (by simpa using label0Line_ne_label1Space), Finset.sum_singleton] at hpyth
  exact hpyth.symm

theorem psiBefore_norm : ‖psiBefore‖ = 1 := by
  unfold psiBefore
  rw [EuclideanSpace.norm_eq, Fin.sum_univ_three]
  have h0 : ((3/5 : ℂ) • (b 0 : H 3) + (4/5 : ℂ) • (b 1 : H 3)) 0 = 3/5 := by
    unfold b; simp [EuclideanSpace.basisFun_apply]
  have h1 : ((3/5 : ℂ) • (b 0 : H 3) + (4/5 : ℂ) • (b 1 : H 3)) 1 = 4/5 := by
    unfold b; simp [EuclideanSpace.basisFun_apply]
  have h2 : ((3/5 : ℂ) • (b 0 : H 3) + (4/5 : ℂ) • (b 1 : H 3)) 2 = 0 := by
    unfold b; simp [EuclideanSpace.basisFun_apply]
  rw [h0, h1, h2]
  norm_num

theorem psiAfter_norm : ‖psiAfter‖ = 1 := by
  rw [← coupleU_psiBefore, coupleU_isometry, psiBefore_norm]

theorem weight_label1Space_before : ‖projL label1Space psiBefore‖ ^ 2 = 16/25 := by
  have h := coarse_weight_sum psiBefore psiBefore_norm
  rw [weight_label0_before] at h
  linarith

theorem weight_label1Space_after : ‖projL label1Space psiAfter‖ ^ 2 = 16/25 := by
  have h := coarse_weight_sum psiAfter psiAfter_norm
  rw [weight_label0_after] at h
  linarith

/-- The accessible record of a state: its Born weights on the two cells of
`coarsePerspective`, the only cells this witness deems recorded (see
`RefinementNotInRecordAlgebra`). -/
noncomputable def accessibleRecord (x : H 3) : ℝ × ℝ :=
  (‖projL label0Line x‖ ^ 2, ‖projL label1Space x‖ ^ 2)

/-- **FR.** Le deuxième théorème obligatoire : le record accessible est
inchangé par le couplage.

**EN.** The second mandatory theorem: the accessible record is unchanged by
the coupling. -/
theorem recordNeutral_record_eq : accessibleRecord psiBefore = accessibleRecord psiAfter := by
  unfold accessibleRecord
  rw [weight_label0_before, weight_label0_after, weight_label1Space_before, weight_label1Space_after]

/- ================= named "refinement cells not in record algebra" hypothesis ================= -/

/-- **FR.** Hypothèse explicite et nommée : le nom décrit exactement ce que
le type affirme — `anc0Line` et `anc1Line`, deux cellules produites par le
raffinement, ne sont pas des cellules de l'algèbre de records —
`accessibleRecord` n'est construit qu'à partir des deux cellules de
`coarsePerspective`. C'est un choix de modèle contestable, non un théorème
physique. La prose de ce fichier interprète `anc0Line`/`anc1Line` comme les
deux niveaux d'un « ancilla » couplé à la branche observée ; mais `H 3` ne
porte aucune factorisation tensorielle système/ancilla, et rien dans le type
`Submodule ℂ (H 3)` ne distingue une ancilla d'un sous-espace quelconque —
le « couplage » est une rotation interne (`coupleU`) sur un bloc de deux
vecteurs de base, dont l'interprétation physique est stipulée en prose, non
portée par la signature. Un lecteur qui rejette cette hypothèse — par
exemple parce qu'il tient `anc0Line`/`anc1Line` pour directement enregistrés
— rejette le statut record-neutre du raffinement, pas les calculs de poids
bornien.

**EN.** Explicit, named hypothesis: the name describes exactly what the
type states — `anc0Line` and `anc1Line`, two cells produced by the
refinement, are not cells of the record algebra — `accessibleRecord` is
built only from `coarsePerspective`'s two cells. This is a contestable
modeling choice, not a physical theorem. This file's prose interprets
`anc0Line`/`anc1Line` as the two levels of an "ancilla" coupled to the
observed branch; but `H 3` carries no system/ancilla tensor factorization,
and nothing in the type `Submodule ℂ (H 3)` distinguishes an ancilla from
any other subspace — the "coupling" is an internal rotation (`coupleU`) on
a block of two basis vectors, whose physical interpretation is stipulated
in prose, not carried by the signature. A reader who rejects this
hypothesis — for instance by treating `anc0Line`/`anc1Line` as directly
recorded — rejects the refinement's record-neutral status, not the
Born-weight computations. -/
def RefinementNotInRecordAlgebra : Prop :=
  anc0Line ∉ coarsePerspective.cells ∧ anc1Line ∉ coarsePerspective.cells

theorem label0Line_ne_anc0Line : label0Line ≠ anc0Line := by
  intro h
  apply label0Line_ne_bot
  rw [Submodule.eq_bot_iff]
  intro x hx
  have hx' : x ∈ anc0Line := h ▸ hx
  have hxorth : x ∈ label0Lineᗮ := anc0Line_le_label1Space hx'
  rw [Submodule.mem_orthogonal] at hxorth
  exact inner_self_eq_zero.mp (hxorth x hx)

theorem label0Line_ne_anc1Line : label0Line ≠ anc1Line := by
  intro h
  apply label0Line_ne_bot
  rw [Submodule.eq_bot_iff]
  intro x hx
  have hx' : x ∈ anc1Line := h ▸ hx
  have hxorth : x ∈ label0Lineᗮ := anc1Line_le_label1Space hx'
  rw [Submodule.mem_orthogonal] at hxorth
  exact inner_self_eq_zero.mp (hxorth x hx)

theorem anc0Line_ne_label1Space : anc0Line ≠ label1Space := by
  intro h
  have hmem : (b 2 : H 3) ∈ anc0Line := h ▸ anc1Line_le_label1Space (Submodule.mem_span_singleton_self _)
  unfold anc0Line at hmem
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hmem
  have h11 : (⟪(b 1 : H 3), (b 1 : H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b1_unit]; norm_num
  have h12 : (⟪(b 1 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
  rw [← hc, inner_smul_right, h11, mul_one] at h12
  have hb2 : (b 2 : H 3) = 0 := by rw [← hc, h12, zero_smul]
  have : ‖(b 2 : H 3)‖ = 0 := by rw [hb2]; simp
  rw [b2_unit] at this
  norm_num at this

theorem anc1Line_ne_label1Space : anc1Line ≠ label1Space := by
  intro h
  have hmem : (b 1 : H 3) ∈ anc1Line := h ▸ anc0Line_le_label1Space (Submodule.mem_span_singleton_self _)
  unfold anc1Line at hmem
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hmem
  have h22 : (⟪(b 2 : H 3), (b 2 : H 3)⟫_ℂ) = 1 := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast; rw [b2_unit]; norm_num
  have h21 : (⟪(b 2 : H 3), (b 1 : H 3)⟫_ℂ) = 0 := by
    have h12 : (⟪(b 1 : H 3), (b 2 : H 3)⟫_ℂ) = 0 := b.orthonormal.2 (by decide)
    rw [← inner_conj_symm, h12]; simp
  rw [← hc, inner_smul_right, h22, mul_one] at h21
  have hb1 : (b 1 : H 3) = 0 := by rw [← hc, h21, zero_smul]
  have : ‖(b 1 : H 3)‖ = 0 := by rw [hb1]; simp
  rw [b1_unit] at this
  norm_num at this

/-- The stipulated hypothesis holds for this model: with `coarsePerspective`
as the record algebra, neither `anc0Line` nor `anc1Line` is a record cell. -/
theorem refinementNotInRecordAlgebra_holds : RefinementNotInRecordAlgebra := by
  rw [RefinementNotInRecordAlgebra, coarsePerspective_cells_eq]
  simp only [Finset.mem_insert, Finset.mem_singleton]
  refine ⟨?_, ?_⟩
  · push_neg
    exact ⟨fun h => label0Line_ne_anc0Line h.symm, anc0Line_ne_label1Space⟩
  · push_neg
    exact ⟨fun h => label0Line_ne_anc1Line h.symm, anc1Line_ne_label1Space⟩

/- ================= payoff-level and Born-weight invariance ================= -/

/-- The decision-relevant payoff of this witness: it pays off exactly on
`label1Space`, i.e. exactly when the ancilla — whichever of its levels ends
up populated — has *not* recorded the observed branch. -/
noncomputable def payoff : Act 3 := Act.indicator label1Space

/-- **FR.** Le troisième théorème obligatoire : le paiement, tiré en
arrière sur la perspective fine, prend la même valeur (`1`) sur les deux
cellules d'ancilla — la conséquence décisionnelle ne dépend pas du niveau
d'ancilla effectivement peuplé.

**EN.** The third mandatory theorem: the payoff, pulled back to the fine
perspective, takes the same value (`1`) on both ancilla cells — the
decision-relevant consequence does not depend on which ancilla level ends
up populated. -/
theorem recordNeutral_payoff_eq :
    pullbackAct recordNeutral_refines payoff anc0Line = 1 ∧
      pullbackAct recordNeutral_refines payoff anc1Line = 1 := by
  constructor
  · exact (pullbackAct_indicator_eq_one_iff recordNeutral_refines label1Space_mem_coarse
      anc0Line_mem_fine).mpr (by
        rw [mem_coarseCells_iff]; exact ⟨anc0Line_mem_fine, anc0Line_le_label1Space⟩)
  · exact (pullbackAct_indicator_eq_one_iff recordNeutral_refines label1Space_mem_coarse
      anc1Line_mem_fine).mpr (by
        rw [mem_coarseCells_iff]; exact ⟨anc1Line_mem_fine, anc1Line_le_label1Space⟩)

/-- **FR.** Le quatrième théorème obligatoire : les poids borniens des deux
cellules de records sont inchangés par le couplage.

**EN.** The fourth mandatory theorem: the Born weights of the two record
cells are unchanged by the coupling. -/
theorem recordNeutral_bornWeight_eq :
    ‖projL label0Line psiBefore‖ ^ 2 = ‖projL label0Line psiAfter‖ ^ 2 ∧
      ‖projL label1Space psiBefore‖ ^ 2 = ‖projL label1Space psiAfter‖ ^ 2 :=
  ⟨weight_label0_before.trans weight_label0_after.symm,
    weight_label1Space_before.trans weight_label1Space_after.symm⟩

end EverettianProbability.PhysicalRefinement
