import EverettianProbability.Core.Interface
import EverettianProbability.Core.Act
import EverettianProbability.Core.AbstractAct
import EverettianProbability.Core.Nonvacuity
import EverettianProbability.Refinement.PullbackAct
import EverettianProbability.Refinement.PayoffPreserving
import EverettianProbability.Refinement.AbstractPayoffPreserving
import EverettianProbability.Refinement.GlobalPayoffVacuity
import EverettianProbability.Refinement.Nonvacuity
import EverettianProbability.Refinement.NonTriviality
import EverettianProbability.Preference.ExpectationFunctional
import EverettianProbability.Preference.AbstractExpectationFunctional
import EverettianProbability.Preference.Representation
import EverettianProbability.Preference.AbstractRepresentation
import EverettianProbability.Preference.Nonvacuity
import EverettianProbability.Preference.NonTriviality
import EverettianProbability.BornCalibration.ContextualWeight
import EverettianProbability.BornCalibration.AbstractContextualWeight
import EverettianProbability.BornCalibration.RefinementImpliesGrain
import EverettianProbability.BornCalibration.AbstractRefinementImpliesGrain
import EverettianProbability.BornCalibration.BornExpectation
import EverettianProbability.BornCalibration.NonCircularity
import EverettianProbability.BornCalibration.DecisionNonCircularity
import EverettianProbability.BornCalibration.RelativeNecessity
import EverettianProbability.BornCalibration.GrainNecessity
import EverettianProbability.BornCalibration.DimensionNecessity
import EverettianProbability.BornCalibration.DecisionNecessity
import EverettianProbability.BornCalibration.Nonvacuity
import EverettianProbability.Rivals.NaiveBranchCounting
import EverettianProbability.Rivals.FourthPowerWeight
import EverettianProbability.Rivals.Nonvacuity
import EverettianProbability.PhysicalRefinement.RecordNeutralWitness
import EverettianProbability.PhysicalRefinement.Nonvacuity
import EverettianProbability.PhysicalRefinement.NonTriviality
import EverettianProbability.EffectCalibration.EstimationRulePackaging
import EverettianProbability.EffectCalibration.EffectBornExpectation
import EverettianProbability.EffectCalibration.QubitWitness
import EverettianProbability.EffectCalibration.Nonvacuity
import EverettianProbability.EffectCalibration.NonTriviality
import EverettianProbability.Diachronic.Conditioning
import EverettianProbability.Diachronic.NonTriviality
import EverettianProbability.SelfLocation.RecordConditionedCredence
import EverettianProbability.SelfLocation.CredenceUniqueness
import EverettianProbability.SelfLocation.RecordRestrictionIndifference
import EverettianProbability.SelfLocation.UniformCredenceRival
import EverettianProbability.SelfLocation.UniformCredenceRefinementFailure
import EverettianProbability.SelfLocation.DecisionCredenceBridge
import EverettianProbability.Diachronic.ContinuatorCredence
import EverettianProbability.Diachronic.FutureActTotalExpectation
import EverettianProbability.Diachronic.TowerProperty
import EverettianProbability.Diachronic.ThreeLevelTowerWitness
import EverettianProbability.Diachronic.ProjectiveBornContinuators
import EverettianProbability.Diachronic.RecordNeutralPhysicalContinuation
import EverettianProbability.Diachronic.UniformRecordRespectingContinuation
import EverettianProbability.Diachronic.UniformContinuationComposition
import EverettianProbability.Diachronic.UniformContinuationAssociativity
import EverettianProbability.Diachronic.PhysicalBornRatioComposition
import EverettianProbability.Diachronic.ProjectorCommutingContinuation
import EverettianProbability.Diachronic.PhysicalPayoffInvariance
import EverettianProbability.Diachronic.RecordWeightEquivalence
import EverettianProbability.Diachronic.CellwiseOrbitPreparation
import EverettianProbability.Diachronic.EqualNormLocalUnitary
import EverettianProbability.Diachronic.BlockDiagonalRecordOrbit
import EverettianProbability.Diachronic.UnitaryRecordOrbit
import EverettianProbability.Diachronic.FineBornWeightRealization
import EverettianProbability.Diachronic.PhysicalFinePlanContinuation
import EverettianProbability.API.ConditionalBorn
import EverettianProbability.API.DiachronicBorn
import EverettianProbability.API.ConditionalMainResults
import EverettianProbability.API.ExactFinitePhysicalRichness
import EverettianProbability.ExactFinite.RecordOrbit
import EverettianProbability.ExactFinite.RefinementRealization
import EverettianProbability.ExactFinite.PhysicalAdequacy
import EverettianProbability.ExactFinite.MainResults
import EverettianProbability.API.ExactFiniteMainResults
import EverettianProbability.API.UpstreamQuantumFoundations
import EverettianProbability.Frequency.HammingCells
import EverettianProbability.Frequency.HammingCounting
import EverettianProbability.Frequency.RepetitionVector
import EverettianProbability.Frequency.CellProjection
import EverettianProbability.Frequency.Distribution
import EverettianProbability.Frequency.Moments
import EverettianProbability.Frequency.Concentration
import EverettianProbability.Frequency.Typicality
import EverettianProbability.Frequency.AsymptoticTypicality
import EverettianProbability.Confirmation.FiniteBayes
import EverettianProbability.Confirmation.FrequencyModel
import EverettianProbability.Confirmation.PosteriorOdds
import EverettianProbability.Confirmation.HypothesisComparison
import EverettianProbability.Confirmation.RationalWitness
import EverettianProbability.Confirmation.SequentialUpdate
import EverettianProbability.Confirmation.FiniteObservationBatch
import EverettianProbability.Confirmation.IteratedUpdate
import EverettianProbability.Confirmation.BatchPosteriorOdds
import EverettianProbability.Confirmation.FrequencyBatchOdds
import EverettianProbability.Confirmation.RationalBatchWitness
import EverettianProbability.Audit.UpstreamQuantumFoundationsAPI
import EverettianProbability.Audit.PremiseNecessity
import EverettianProbability.Audit.MainResults

/-!
**FR.** Point d'entree du paquet `EverettianProbability`. Il importe, dans
l'ordre de dependance, `Core`, `Refinement`, `Preference`, `BornCalibration`,
`PhysicalRefinement`, `EffectCalibration`, `SelfLocation`, `Diachronic`, les
facades API conditionnelle et physique exacte, `Frequency`, `Confirmation` et
`Audit`. `SelfLocation` formalise une credence conditionnee par record sous
premisses semantiques explicites. `Diachronic` formalise des continuateurs,
l'esperance totale, la chaine, la tour, la composition et des continuations
physiques exactes. L'API conditionnelle est stable en `v1.x`; l'API physique
exacte reste experimentale. `BornCalibration` inclut desormais le contre-modele
niveau decision (`DecisionNonCircularity`), dans la fermeture du build public
principal aux cotes du contre-modele niveau poids (`NonCircularity`). Aucune
norme rationnelle n'est derivee de la seule dynamique unitaire.

**EN.** Entry point of the `EverettianProbability` package. It imports, in
dependency order, `Core`, `Refinement`, `Preference`, `BornCalibration`,
`PhysicalRefinement`, `EffectCalibration`, `SelfLocation`, `Diachronic`, the
conditional and exact-physical API facades, `Frequency`, `Confirmation`, and
`Audit`. `SelfLocation` formalizes record-conditioned credence under explicit
semantic premises. `Diachronic` formalizes continuators, total expectation,
chain, tower, composition, and exact physical continuations. The conditional
API is stable in `v1.x`; the exact-physical API remains experimental.
`BornCalibration` now includes the decision-level countermodel
(`DecisionNonCircularity`), in the main public build closure alongside the
weight-level countermodel (`NonCircularity`). No rational norm is derived
from unitary dynamics alone.
-/