import EverettianProbability.BornCalibration.RelativeNecessity

/-!
# Relative necessity of Grain coherence

This file supplies `W4` of the JAR L0 campaign.  The witness is the
context-normalized amplitude rule

`E(D,c) = ‖P_c v‖ / ∑ d ∈ D.cells, ‖P_d v‖`.

For a unit state its denominator is strictly positive on every perspective,
so the rule is normalized, positive, and null on cells orthogonal to the
state.  It is nevertheless not refinement-additive.  An explicit dimension-
three state exhibits the failure between the standard one-dimensional
perspective and the binary perspective generated by the first basis line.
-/

namespace EverettianProbability.BornCalibration

open QuantumFoundations.ProbabilityAPI
open QuantumFoundations.ProbabilityAPI.BornRule
open scoped Classical InnerProductSpace

noncomputable section

/-- Sum of projection amplitudes used to normalize the `p = 1` witness. -/
def amplitudeDenom {n : ℕ} (v : H n) (D : Perspective n) : ℝ :=
  ∑ c ∈ D.cells, ‖projL c v‖

/-- Context-normalized projection amplitude (`p = 1`, rather than Born's `p = 2`). -/
def amplitudeWeight {n : ℕ} (v : H n) :
    Perspective n → Submodule ℂ (H n) → ℝ :=
  fun D c => ‖projL c v‖ / amplitudeDenom v D

private theorem projL_top_apply {n : ℕ} (v : H n) :
    projL (⊤ : Submodule ℂ (H n)) v = v := by
  unfold projL
  rw [Submodule.starProjection_top]
  rfl

private theorem sum_sq_projL_cells_eq_one {n : ℕ} {v : H n}
    (hv : ‖v‖ = 1) (D : Perspective n) :
    ∑ c ∈ D.cells, ‖projL c v‖ ^ 2 = 1 := by
  have htop : D.cells.sup id = (⊤ : Submodule ℂ (H n)) := by
    rw [Finset.sup_id_eq_sSup]
    exact D.span
  have h := QuantumFoundations.BornRule.sum_sq_projL_of_pairwise_isOrtho
    D.cells
    (fun c hc c' hc' hne => D.ortho c hc c' hc' hne)
    v
  rw [htop, projL_top_apply, hv] at h
  norm_num at h
  exact h.symm

/-- For a unit vector, the amplitude denominator is strictly positive in every
perspective. -/
theorem amplitudeDenom_pos {n : ℕ} {v : H n} (hv : ‖v‖ = 1)
    (D : Perspective n) : 0 < amplitudeDenom v D := by
  have hnonneg : 0 ≤ amplitudeDenom v D := by
    unfold amplitudeDenom
    exact Finset.sum_nonneg (fun c _ => norm_nonneg (projL c v))
  have hne : amplitudeDenom v D ≠ 0 := by
    intro hzero
    have hterm : ∀ c ∈ D.cells, ‖projL c v‖ = 0 := by
      intro c hc
      have hle : ‖projL c v‖ ≤ amplitudeDenom v D := by
        unfold amplitudeDenom
        exact Finset.single_le_sum (fun d _ => norm_nonneg (projL d v)) hc
      rw [hzero] at hle
      exact le_antisymm hle (norm_nonneg _)
    have hsquares_zero : ∑ c ∈ D.cells, ‖projL c v‖ ^ 2 = 0 := by
      apply Finset.sum_eq_zero
      intro c hc
      rw [hterm c hc]
      norm_num
    rw [sum_sq_projL_cells_eq_one hv D] at hsquares_zero
    norm_num at hsquares_zero
  exact lt_of_le_of_ne hnonneg hne.symm

theorem amplitudeWeight_axNorm {n : ℕ} {v : H n} (hv : ‖v‖ = 1) :
    AxNorm (amplitudeWeight v) := by
  intro D
  change (∑ c ∈ D.cells, ‖projL c v‖ / amplitudeDenom v D) = 1
  rw [← Finset.sum_div]
  change amplitudeDenom v D / amplitudeDenom v D = 1
  exact div_self (ne_of_gt (amplitudeDenom_pos hv D))

theorem amplitudeWeight_axPos {n : ℕ} {v : H n} (hv : ‖v‖ = 1) :
    AxPos (amplitudeWeight v) := by
  intro D c hc
  exact div_nonneg (norm_nonneg _) (le_of_lt (amplitudeDenom_pos hv D))

theorem amplitudeWeight_axNul {n : ℕ} {v : H n} (hv : ‖v‖ = 1) :
    AxNul (amplitudeWeight v) v := by
  intro D c hc horth
  have hp : projL c v = 0 := by
    change c.starProjection v = 0
    exact (Submodule.starProjection_apply_eq_zero_iff c).mpr horth
  simp [amplitudeWeight, hp]

/-! ## Explicit dimension-three failure of Grain -/

/-- Third computational-basis vector. -/
def l0e2 : H 3 := EuclideanSpace.single (2 : Fin 3) (1 : ℂ)

def l0Line1 : Submodule ℂ (H 3) := ℂ ∙ l0e1

def l0Line2 : Submodule ℂ (H 3) := ℂ ∙ l0e2

theorem l0e2_norm : ‖l0e2‖ = 1 := by
  simp [l0e2]

/-- Canonical orthonormal basis of `H 3`. -/
def l0Basis3 : OrthonormalBasis (Fin 3) ℂ (H 3) :=
  EuclideanSpace.basisFun (Fin 3) ℂ

private theorem l0Basis3_apply (i : Fin 3) :
    (l0Basis3 i : H 3) = EuclideanSpace.single i (1 : ℂ) := by
  simp [l0Basis3]

private theorem l0Basis3_line_zero :
    (ℂ ∙ (l0Basis3 (0 : Fin 3) : H 3)) = l0Line0 := by
  simp [l0Basis3_apply, l0Line0, l0e0]

private theorem l0Basis3_line_one :
    (ℂ ∙ (l0Basis3 (1 : Fin 3) : H 3)) = l0Line1 := by
  simp [l0Basis3_apply, l0Line1, l0e1]

private theorem l0Basis3_line_two :
    (ℂ ∙ (l0Basis3 (2 : Fin 3) : H 3)) = l0Line2 := by
  simp [l0Basis3_apply, l0Line2, l0e2]

/-- Fine context resolving all three computational lines. -/
def l0Fine : Perspective 3 :=
  QuantumFoundations.BornRule.basisPerspective l0Basis3

/-- Coarse context resolving only the first computational line and its
orthogonal complement. -/
def l0Coarse : Perspective 3 :=
  Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top

private theorem l0Line0_mem_fine : l0Line0 ∈ l0Fine.cells := by
  change l0Line0 ∈ Finset.univ.image
    (fun i : Fin 3 => ℂ ∙ (l0Basis3 i : H 3))
  rw [Finset.mem_image]
  exact ⟨0, Finset.mem_univ _, l0Basis3_line_zero⟩

private theorem l0Line0_mem_coarse : l0Line0 ∈ l0Coarse.cells := by
  exact Finset.mem_insert_self _ _

private theorem l0Line0orth_mem_coarse : l0Line0ᗮ ∈ l0Coarse.cells := by
  exact Finset.mem_insert_of_mem (Finset.mem_singleton_self _)

private theorem inner_l0e0_l0e2 : ⟪l0e0, l0e2⟫_ℂ = 0 := by
  unfold l0e0 l0e2
  rw [EuclideanSpace.inner_single_left]
  norm_num [show (0 : Fin 3) ≠ (2 : Fin 3) by decide]

private theorem l0e2_mem_l0Line0_orthogonal : l0e2 ∈ l0Line0ᗮ := by
  unfold l0Line0
  rw [Submodule.mem_orthogonal]
  intro x hx
  obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.mp hx
  rw [inner_smul_left, inner_l0e0_l0e2, mul_zero]

/-- The standard three-line perspective refines the binary perspective. -/
theorem l0Fine_refines_l0Coarse : Refines l0Fine l0Coarse := by
  intro c hc
  change c ∈ Finset.univ.image
    (fun i : Fin 3 => ℂ ∙ (l0Basis3 i : H 3)) at hc
  rw [Finset.mem_image] at hc
  obtain ⟨i, hi, rfl⟩ := hc
  have hi_cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases hi_cases with h0 | h1 | h2
  · refine ⟨l0Line0, l0Line0_mem_coarse, ?_⟩
    rw [h0, l0Basis3_line_zero]
  · refine ⟨l0Line0ᗮ, l0Line0orth_mem_coarse, ?_⟩
    rw [h1, l0Basis3_line_one, Submodule.span_singleton_le_iff_mem]
    exact l0e1_mem_l0Line0_orthogonal
  · refine ⟨l0Line0ᗮ, l0Line0orth_mem_coarse, ?_⟩
    rw [h2, l0Basis3_line_two, Submodule.span_singleton_le_iff_mem]
    exact l0e2_mem_l0Line0_orthogonal

/-- Unit state with three nonzero amplitudes `3/5`, `12/25`, and `16/25`. -/
def l0vGrain : H 3 :=
  (3 / 5 : ℂ) • l0e0 + (12 / 25 : ℂ) • l0e1 + (16 / 25 : ℂ) • l0e2

private theorem l0vGrain_zero : l0vGrain 0 = (3 / 5 : ℂ) := by
  norm_num [l0vGrain, l0e0, l0e1, l0e2,
    show (0 : Fin 3) ≠ (1 : Fin 3) by decide,
    show (0 : Fin 3) ≠ (2 : Fin 3) by decide]

private theorem l0vGrain_one : l0vGrain 1 = (12 / 25 : ℂ) := by
  norm_num [l0vGrain, l0e0, l0e1, l0e2,
    show (1 : Fin 3) ≠ (0 : Fin 3) by decide,
    show (1 : Fin 3) ≠ (2 : Fin 3) by decide]

private theorem l0vGrain_two : l0vGrain 2 = (16 / 25 : ℂ) := by
  norm_num [l0vGrain, l0e0, l0e1, l0e2,
    show (2 : Fin 3) ≠ (0 : Fin 3) by decide,
    show (2 : Fin 3) ≠ (1 : Fin 3) by decide]

theorem l0vGrain_norm : ‖l0vGrain‖ = 1 := by
  rw [EuclideanSpace.norm_eq, Fin.sum_univ_three,
    l0vGrain_zero, l0vGrain_one, l0vGrain_two]
  norm_num

private theorem inner_l0e0_l0vGrain :
    ⟪l0e0, l0vGrain⟫_ℂ = (3 / 5 : ℂ) := by
  unfold l0e0
  rw [EuclideanSpace.inner_single_left, l0vGrain_zero]
  norm_num

private theorem inner_l0e1_l0vGrain :
    ⟪l0e1, l0vGrain⟫_ℂ = (12 / 25 : ℂ) := by
  unfold l0e1
  rw [EuclideanSpace.inner_single_left, l0vGrain_one]
  norm_num

private theorem inner_l0e2_l0vGrain :
    ⟪l0e2, l0vGrain⟫_ℂ = (16 / 25 : ℂ) := by
  unfold l0e2
  rw [EuclideanSpace.inner_single_left, l0vGrain_two]
  norm_num

private theorem projL_l0Line0_l0vGrain :
    projL l0Line0 l0vGrain = (3 / 5 : ℂ) • l0e0 := by
  unfold l0Line0
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit l0e0 l0vGrain l0e0_norm,
    inner_l0e0_l0vGrain]

private theorem projL_l0Line1_l0vGrain :
    projL l0Line1 l0vGrain = (12 / 25 : ℂ) • l0e1 := by
  unfold l0Line1
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit l0e1 l0vGrain l0e1_norm,
    inner_l0e1_l0vGrain]

private theorem projL_l0Line2_l0vGrain :
    projL l0Line2 l0vGrain = (16 / 25 : ℂ) • l0e2 := by
  unfold l0Line2
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit l0e2 l0vGrain l0e2_norm,
    inner_l0e2_l0vGrain]

private theorem projL_l0Line0_l0vGrain_norm :
    ‖projL l0Line0 l0vGrain‖ = 3 / 5 := by
  rw [projL_l0Line0_l0vGrain, norm_smul, l0e0_norm]
  norm_num

private theorem projL_l0Line1_l0vGrain_norm :
    ‖projL l0Line1 l0vGrain‖ = 12 / 25 := by
  rw [projL_l0Line1_l0vGrain, norm_smul, l0e1_norm]
  norm_num

private theorem projL_l0Line2_l0vGrain_norm :
    ‖projL l0Line2 l0vGrain‖ = 16 / 25 := by
  rw [projL_l0Line2_l0vGrain, norm_smul, l0e2_norm]
  norm_num

private theorem projL_l0Line0orth_l0vGrain_norm :
    ‖projL l0Line0ᗮ l0vGrain‖ = 4 / 5 := by
  have h := Submodule.norm_sq_eq_add_norm_sq_starProjection l0vGrain l0Line0
  change ‖l0vGrain‖ ^ 2 =
    ‖projL l0Line0 l0vGrain‖ ^ 2 + ‖projL l0Line0ᗮ l0vGrain‖ ^ 2 at h
  rw [l0vGrain_norm, projL_l0Line0_l0vGrain_norm] at h
  have hn := norm_nonneg (projL l0Line0ᗮ l0vGrain)
  nlinarith

private theorem l0Line0_ne_l0Line0orth : l0Line0 ≠ l0Line0ᗮ := by
  intro heq
  have hmem : l0e0 ∈ l0Line0 := Submodule.mem_span_singleton_self l0e0
  have horth : l0e0 ∈ l0Line0ᗮ := by rwa [← heq]
  have hz : ⟪l0e0, l0e0⟫_ℂ = 0 :=
    (Submodule.mem_orthogonal l0Line0 l0e0).mp horth l0e0 hmem
  have he0 : l0e0 = 0 := inner_self_eq_zero.mp hz
  have hnorm := l0e0_norm
  rw [he0, norm_zero] at hnorm
  norm_num at hnorm

private theorem amplitudeDenom_l0Coarse :
    amplitudeDenom l0vGrain l0Coarse = 7 / 5 := by
  change Finset.sum ({l0Line0, l0Line0ᗮ} : Finset (Submodule ℂ (H 3)))
    (fun c => ‖projL c l0vGrain‖) = 7 / 5
  have hnotmem : l0Line0 ∉ ({l0Line0ᗮ} : Finset (Submodule ℂ (H 3))) := by
    simpa using l0Line0_ne_l0Line0orth
  rw [Finset.sum_insert hnotmem, Finset.sum_singleton,
    projL_l0Line0_l0vGrain_norm, projL_l0Line0orth_l0vGrain_norm]
  norm_num

private theorem amplitudeDenom_l0Fine :
    amplitudeDenom l0vGrain l0Fine = 43 / 25 := by
  change Finset.sum (Finset.univ.image
      (fun i : Fin 3 => ℂ ∙ (l0Basis3 i : H 3)))
      (fun c => ‖projL c l0vGrain‖) = 43 / 25
  rw [Finset.sum_image (QuantumFoundations.BornRule.line_injective l0Basis3)]
  rw [Fin.sum_univ_three]
  rw [l0Basis3_line_zero, l0Basis3_line_one, l0Basis3_line_two,
    projL_l0Line0_l0vGrain_norm, projL_l0Line1_l0vGrain_norm,
    projL_l0Line2_l0vGrain_norm]
  norm_num

private theorem amplitudeWeight_l0Coarse_line0 :
    amplitudeWeight l0vGrain l0Coarse l0Line0 = 3 / 7 := by
  rw [amplitudeWeight, projL_l0Line0_l0vGrain_norm, amplitudeDenom_l0Coarse]
  norm_num

private theorem amplitudeWeight_l0Fine_line0 :
    amplitudeWeight l0vGrain l0Fine l0Line0 = 15 / 43 := by
  rw [amplitudeWeight, projL_l0Line0_l0vGrain_norm, amplitudeDenom_l0Fine]
  norm_num

private theorem l0Fine_filter_line0 :
    l0Fine.cells.filter (· ≤ l0Line0) = {l0Line0} := by
  apply Finset.eq_singleton_iff_unique_mem.mpr
  refine ⟨Finset.mem_filter.mpr ⟨l0Line0_mem_fine, le_refl l0Line0⟩, ?_⟩
  intro c hc
  obtain ⟨hcmem, hcle⟩ := Finset.mem_filter.mp hc
  exact l0Fine.unique_parent hcmem l0Line0_mem_fine
    (l0Fine.nz c hcmem) (le_refl c) hcle

theorem amplitudeWeight_not_axGrain : ¬ AxGrain (amplitudeWeight l0vGrain) := by
  intro hGrain
  have h := hGrain l0Fine l0Coarse l0Fine_refines_l0Coarse
    l0Line0 l0Line0_mem_coarse
  rw [l0Fine_filter_line0, Finset.sum_singleton,
    amplitudeWeight_l0Coarse_line0, amplitudeWeight_l0Fine_line0] at h
  norm_num at h

private theorem amplitudeWeight_not_born_on_line0 :
    amplitudeWeight l0vGrain l0Coarse l0Line0 ≠
      ‖projL l0Line0 l0vGrain‖ ^ 2 := by
  rw [amplitudeWeight_l0Coarse_line0, projL_l0Line0_l0vGrain_norm]
  norm_num

/--
`W4`. Relative necessity of Grain coherence at the exact public weight-level
interface.  The retained normalization, positivity, unit-state, and null-support
premises all hold globally for the normalized-amplitude rule.  On the explicit
fine/coarse pair, Grain would require `3/7 = 15/43`, and the same coarse cell
also falsifies the Born conclusion (`3/7 ≠ 9/25`).
-/
theorem w4_remove_axGrain :
    ∃ (Est : Perspective 3 → Submodule ℂ (H 3) → ℝ) (v : H 3),
      3 ≤ (3 : ℕ) ∧
      AxNorm Est ∧
      AxPos Est ∧
      ‖v‖ = 1 ∧
      AxNul Est v ∧
      ¬ AxGrain Est ∧
      ∃ (D : Perspective 3) (c : Submodule ℂ (H 3)),
        c ∈ D.cells ∧ Est D c ≠ ‖projL c v‖ ^ 2 := by
  refine ⟨amplitudeWeight l0vGrain, l0vGrain, by norm_num,
    amplitudeWeight_axNorm l0vGrain_norm,
    amplitudeWeight_axPos l0vGrain_norm,
    l0vGrain_norm,
    amplitudeWeight_axNul l0vGrain_norm,
    amplitudeWeight_not_axGrain,
    l0Coarse, l0Line0, l0Line0_mem_coarse,
    amplitudeWeight_not_born_on_line0⟩

end

end EverettianProbability.BornCalibration