import EverettianProbability.BornCalibration.BornExpectation
import EverettianProbability.BornCalibration.DecisionNonCircularity

/-!
# Relative necessity of exposed Born-calibration premises

This file implements the L0 campaign used in the JAR revision.  Each deletion
witness is required to (A) satisfy every retained premise of the public theorem,
(B) falsify that theorem's exact Born conclusion on an explicit perspective and
cell, and (C) explicitly violate the removed premise.

The campaign is carried out downstream in `everettian-probability-lean`; no
upstream API change is required.
-/

namespace EverettianProbability.BornCalibration

open QuantumFoundations.ProbabilityAPI
open QuantumFoundations.ProbabilityAPI.BornRule
open scoped Classical InnerProductSpace

noncomputable section

/-! ## Common dimension-three witness geometry -/

/-- First computational-basis vector in `H 3`. -/
def l0e0 : H 3 := EuclideanSpace.single (0 : Fin 3) (1 : ℂ)

theorem l0e0_norm : ‖l0e0‖ = 1 := by
  simp [l0e0]

private theorem l0e0_ne_zero : l0e0 ≠ 0 := by
  intro h
  have hnorm := l0e0_norm
  rw [h, norm_zero] at hnorm
  norm_num at hnorm

/-- The line generated by `l0e0`. -/
def l0Line0 : Submodule ℂ (H 3) := ℂ ∙ l0e0

private theorem l0Line0_finrank : Module.finrank ℂ l0Line0 = 1 :=
  finrank_span_singleton l0e0_ne_zero

theorem l0Line0_ne_bot : l0Line0 ≠ ⊥ := by
  rw [Submodule.ne_bot_iff]
  exact ⟨l0e0, Submodule.mem_span_singleton_self l0e0, l0e0_ne_zero⟩

theorem l0Line0_ne_top : l0Line0 ≠ ⊤ := by
  intro h
  have h1 := l0Line0_finrank
  rw [h, finrank_top] at h1
  simp at h1

private theorem projL_l0Line0_l0e0 : projL l0Line0 l0e0 = l0e0 := by
  unfold l0Line0
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit _ _ l0e0_norm]
  simp [l0e0]

/-! ## W1 — remove `AxNorm` -/

/-- The identically-zero weight rule in dimension three. -/
def zeroWeight3 : Perspective 3 → Submodule ℂ (H 3) → ℝ := fun _ _ => 0

theorem zeroWeight3_axGrain : AxGrain zeroWeight3 := by
  intro D' D hRefines c hc
  simp [zeroWeight3]

theorem zeroWeight3_axPos : AxPos zeroWeight3 := by
  intro D c hc
  simp [zeroWeight3]

theorem zeroWeight3_axNul (v : H 3) : AxNul zeroWeight3 v := by
  intro D c hc hv
  simp [zeroWeight3]

theorem zeroWeight3_not_axNorm : ¬ AxNorm zeroWeight3 := by
  intro hNorm
  have h := hNorm (Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top)
  norm_num [zeroWeight3] at h

theorem zeroWeight3_not_born_on_line0 :
    zeroWeight3
        (Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top) l0Line0 ≠
      ‖projL l0Line0 l0e0‖ ^ 2 := by
  rw [projL_l0Line0_l0e0, l0e0_norm]
  norm_num [zeroWeight3]

/--
`W1`.  Relative necessity of the exposed normalization premise at the exact
weight-level interface of `grainCoherenceTheorem_projector`.

All retained premises hold in dimension three, normalization itself fails,
and the exact Born conclusion fails on the explicit binary perspective with
cell `l0Line0`.
-/
theorem w1_remove_axNorm :
    ∃ (Est : Perspective 3 → Submodule ℂ (H 3) → ℝ) (v : H 3),
      3 ≤ (3 : ℕ) ∧
      AxGrain Est ∧
      AxPos Est ∧
      ‖v‖ = 1 ∧
      AxNul Est v ∧
      ¬ AxNorm Est ∧
      ∃ (D : Perspective 3) (c : Submodule ℂ (H 3)),
        c ∈ D.cells ∧ Est D c ≠ ‖projL c v‖ ^ 2 := by
  refine ⟨zeroWeight3, l0e0, by norm_num, zeroWeight3_axGrain,
    zeroWeight3_axPos, l0e0_norm, zeroWeight3_axNul l0e0,
    zeroWeight3_not_axNorm,
    Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top, l0Line0,
    Finset.mem_insert_self _ _, zeroWeight3_not_born_on_line0⟩

end

end EverettianProbability.BornCalibration
