import EverettianProbability.BornCalibration.BornExpectation
import EverettianProbability.BornCalibration.DecisionNonCircularity

/-!
# Relative necessity of exposed Born-calibration premises

This file implements the L0 campaign used in the JAR revision.  Each deletion
witness is required to (A) satisfy every retained premise of the public theorem,
(B) falsify that theorem's exact Born conclusion on an explicit perspective and
cell, and (C) explicitly violate the removed premise.

The campaign is carried out downstream in `everettian-probability-lean`; no
upstream API change is required.
-/

namespace EverettianProbability.BornCalibration

open QuantumFoundations.ProbabilityAPI
open QuantumFoundations.ProbabilityAPI.BornRule
open scoped Classical InnerProductSpace

noncomputable section

/-! ## Common dimension-three witness geometry -/

/-- First computational-basis vector in `H 3`. -/
def l0e0 : H 3 := EuclideanSpace.single (0 : Fin 3) (1 : ℂ)

/-- Second computational-basis vector in `H 3`. -/
def l0e1 : H 3 := EuclideanSpace.single (1 : Fin 3) (1 : ℂ)

theorem l0e0_norm : ‖l0e0‖ = 1 := by
  simp [l0e0]

theorem l0e1_norm : ‖l0e1‖ = 1 := by
  simp [l0e1]

private theorem l0e0_ne_zero : l0e0 ≠ 0 := by
  intro h
  have hnorm := l0e0_norm
  rw [h, norm_zero] at hnorm
  norm_num at hnorm

/-- The line generated by `l0e0`. -/
def l0Line0 : Submodule ℂ (H 3) := ℂ ∙ l0e0

private theorem l0Line0_finrank : Module.finrank ℂ l0Line0 = 1 :=
  finrank_span_singleton l0e0_ne_zero

theorem l0Line0_ne_bot : l0Line0 ≠ ⊥ := by
  rw [Submodule.ne_bot_iff]
  exact ⟨l0e0, Submodule.mem_span_singleton_self l0e0, l0e0_ne_zero⟩

theorem l0Line0_ne_top : l0Line0 ≠ ⊤ := by
  intro h
  have h1 := l0Line0_finrank
  rw [h, finrank_top] at h1
  simp at h1

private theorem projL_l0Line0_l0e0 : projL l0Line0 l0e0 = l0e0 := by
  unfold l0Line0
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit _ _ l0e0_norm]
  simp [l0e0]

private theorem projL_l0Line0_l0e1 : projL l0Line0 l0e1 = 0 := by
  unfold l0Line0
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit _ _ l0e0_norm]
  simp [l0e0, l0e1]

theorem l0e1_mem_l0Line0_orthogonal : l0e1 ∈ l0Line0ᗮ := by
  have hzero := projL_l0Line0_l0e1
  unfold projL at hzero
  rw [ContinuousLinearMap.coe_coe] at hzero
  exact (Submodule.starProjection_apply_eq_zero_iff l0Line0).mp hzero

/-! ## W1 — remove `AxNorm` -/

/-- The identically-zero weight rule in dimension three. -/
def zeroWeight3 : Perspective 3 → Submodule ℂ (H 3) → ℝ := fun _ _ => 0

theorem zeroWeight3_axGrain : AxGrain zeroWeight3 := by
  intro D' D hRefines c hc
  simp [zeroWeight3]

theorem zeroWeight3_axPos : AxPos zeroWeight3 := by
  intro D c hc
  simp [zeroWeight3]

theorem zeroWeight3_axNul (v : H 3) : AxNul zeroWeight3 v := by
  intro D c hc hv
  simp [zeroWeight3]

theorem zeroWeight3_not_axNorm : ¬ AxNorm zeroWeight3 := by
  intro hNorm
  have h := hNorm (Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top)
  norm_num [zeroWeight3] at h

theorem zeroWeight3_not_born_on_line0 :
    zeroWeight3
        (Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top) l0Line0 ≠
      ‖projL l0Line0 l0e0‖ ^ 2 := by
  rw [projL_l0Line0_l0e0, l0e0_norm]
  norm_num [zeroWeight3]

/--
`W1`.  Relative necessity of the exposed normalization premise at the exact
weight-level interface of `grainCoherenceTheorem_projector`.

All retained premises hold in dimension three, normalization itself fails,
and the exact Born conclusion fails on the explicit binary perspective with
cell `l0Line0`.
-/
theorem w1_remove_axNorm :
    ∃ (Est : Perspective 3 → Submodule ℂ (H 3) → ℝ) (v : H 3),
      3 ≤ (3 : ℕ) ∧
      AxGrain Est ∧
      AxPos Est ∧
      ‖v‖ = 1 ∧
      AxNul Est v ∧
      ¬ AxNorm Est ∧
      ∃ (D : Perspective 3) (c : Submodule ℂ (H 3)),
        c ∈ D.cells ∧ Est D c ≠ ‖projL c v‖ ^ 2 := by
  refine ⟨zeroWeight3, l0e0, by norm_num, zeroWeight3_axGrain,
    zeroWeight3_axPos, l0e0_norm, zeroWeight3_axNul l0e0,
    zeroWeight3_not_axNorm,
    Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top, l0Line0,
    Finset.mem_insert_self _ _, zeroWeight3_not_born_on_line0⟩

/-! ## W2 — remove `AxNul` -/

/-- The Born weight of `l0e0` violates null support relative to the orthogonal
unit state `l0e1`. -/
theorem bornE0_not_axNul_l0e1 : ¬ AxNul (E₀ l0e0) l0e1 := by
  intro hNul
  have h := hNul
    (Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top)
    l0Line0 (Finset.mem_insert_self _ _) l0e1_mem_l0Line0_orthogonal
  change ‖projL l0Line0 l0e0‖ ^ 2 = 0 at h
  rw [projL_l0Line0_l0e0, l0e0_norm] at h
  norm_num at h

theorem bornE0_not_born_for_l0e1_on_line0 :
    E₀ l0e0
        (Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top) l0Line0 ≠
      ‖projL l0Line0 l0e1‖ ^ 2 := by
  change ‖projL l0Line0 l0e0‖ ^ 2 ≠ ‖projL l0Line0 l0e1‖ ^ 2
  rw [projL_l0Line0_l0e0, projL_l0Line0_l0e1, l0e0_norm]
  norm_num

/--
`W2`. Relative necessity of the exposed canonical null-support premise.
The retained Grain/Norm/Pos premises are supplied by the ordinary Born weight
of `l0e0`, while the tested state is the orthogonal unit vector `l0e1`.
-/
theorem w2_remove_axNul :
    ∃ (Est : Perspective 3 → Submodule ℂ (H 3) → ℝ) (v : H 3),
      3 ≤ (3 : ℕ) ∧
      AxGrain Est ∧
      AxNorm Est ∧
      AxPos Est ∧
      ‖v‖ = 1 ∧
      ¬ AxNul Est v ∧
      ∃ (D : Perspective 3) (c : Submodule ℂ (H 3)),
        c ∈ D.cells ∧ Est D c ≠ ‖projL c v‖ ^ 2 := by
  refine ⟨E₀ l0e0, l0e1, by norm_num, E₀_isGrain l0e0,
    E₀_isNorm l0e0 l0e0_norm, E₀_isPos l0e0, l0e1_norm,
    bornE0_not_axNul_l0e1,
    Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top, l0Line0,
    Finset.mem_insert_self _ _, bornE0_not_born_for_l0e1_on_line0⟩

/-! ## W3 — remove `‖v‖ = 1` -/

/-- A deliberately non-unit test vector with the same support line as `l0e0`. -/
def l0v2 : H 3 := (2 : ℂ) • l0e0

theorem l0v2_norm : ‖l0v2‖ = 2 := by
  simp [l0v2, norm_smul, l0e0_norm]

theorem l0v2_not_unit : ‖l0v2‖ ≠ 1 := by
  rw [l0v2_norm]
  norm_num

/-- Null support for the Born weight of `l0e0` is unchanged when the tested
vector is rescaled by the nonzero scalar `2`. -/
theorem bornE0_axNul_l0v2 : AxNul (E₀ l0e0) l0v2 := by
  intro D c hc hv
  apply E₀_isNul l0e0 D c hc
  have h := cᗮ.smul_mem (1 / 2 : ℂ) hv
  simpa [l0v2, smul_smul] using h

private theorem projL_l0Line0_l0v2 : projL l0Line0 l0v2 = l0v2 := by
  rw [l0v2, map_smul, projL_l0Line0_l0e0]

theorem bornE0_not_born_for_l0v2_on_line0 :
    E₀ l0e0
        (Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top) l0Line0 ≠
      ‖projL l0Line0 l0v2‖ ^ 2 := by
  change ‖projL l0Line0 l0e0‖ ^ 2 ≠ ‖projL l0Line0 l0v2‖ ^ 2
  rw [projL_l0Line0_l0e0, projL_l0Line0_l0v2, l0e0_norm, l0v2_norm]
  norm_num

/--
`W3`. Relative necessity of the exposed unit-norm premise. The weight rule is
Born for the unit vector `l0e0`; the theorem is tested instead at `2 • l0e0`.
All other exposed premises hold, the norm premise explicitly fails, and the
exact projector conclusion gives `1 ≠ 4` on `l0Line0`.
-/
theorem w3_remove_unit_norm :
    ∃ (Est : Perspective 3 → Submodule ℂ (H 3) → ℝ) (v : H 3),
      3 ≤ (3 : ℕ) ∧
      AxGrain Est ∧
      AxNorm Est ∧
      AxPos Est ∧
      AxNul Est v ∧
      ‖v‖ ≠ 1 ∧
      ∃ (D : Perspective 3) (c : Submodule ℂ (H 3)),
        c ∈ D.cells ∧ Est D c ≠ ‖projL c v‖ ^ 2 := by
  refine ⟨E₀ l0e0, l0v2, by norm_num, E₀_isGrain l0e0,
    E₀_isNorm l0e0 l0e0_norm, E₀_isPos l0e0, bornE0_axNul_l0v2,
    l0v2_not_unit,
    Perspective.binary l0Line0 l0Line0_ne_bot l0Line0_ne_top, l0Line0,
    Finset.mem_insert_self _ _, bornE0_not_born_for_l0v2_on_line0⟩

end

end EverettianProbability.BornCalibration
