import EverettianProbability.Diachronic.UnitaryRecordOrbit

/-!
**FR.** # Orbite unitaire exacte d'un record

Cette facade experimentale caracterise les etats de meme record bornien par
l'existence d'un unitaire commutant avec tous les projecteurs du record. Le
resultat est exact et de dimension finie; aucune naturalite hamiltonienne ni
modele de decoherence n'est affirme.

**EN.** # Exact unitary orbit of a record

This experimental facade characterizes states with the same Born record by
the existence of a unitary commuting with every record projector. The result
is exact and finite-dimensional; it asserts neither Hamiltonian naturalness
nor a decoherence model.
-/

namespace EverettianProbability.ExactFinite

open QuantumFoundations.BornRule Gleason
open QuantumFoundations.ProbabilityAPI
open EverettianProbability.Core
open EverettianProbability.Abstract
open scoped BigOperators Classical InnerProductSpace

noncomputable section

variable {n : ℕ}

/-- Equality of the complete Born record on a finite projective perspective. -/
abbrev SameRecord
    (D : Perspective n)
    (x y : H n) : Prop :=
  EverettianProbability.Abstract.SameBornRecord D x y

/-- Orbit generated by global unitaries commuting with every projector of the
record perspective. -/
abbrev RecordUnitaryOrbit
    (D : Perspective n)
    (x y : H n) : Prop :=
  EverettianProbability.Abstract.ProjectorCommutingUnitaryOrbit D x y

/-- Explicit witness that two states are related by a projector-commuting
unitary. -/
structure RecordUnitaryWitness
    (D : Perspective n)
    (x y : H n) where
  unitary : H n ≃ₗᵢ[ℂ] H n
  commutes : CommutesWithPerspectiveProjectors D unitary.toLinearEquiv.toLinearMap
  maps_state : unitary x = y

namespace RecordUnitaryWitness

theorem toOrbit
    {D : Perspective n}
    {x y : H n}
    (W : RecordUnitaryWitness D x y) :
    RecordUnitaryOrbit D x y :=
  ⟨W.unitary, W.commutes, W.maps_state⟩

theorem sameRecord
    {D : Perspective n}
    {x y : H n}
    (W : RecordUnitaryWitness D x y) :
    SameRecord D x y := by
  exact sameBornRecord_of_projectorCommutingUnitaryOrbit W.toOrbit

end RecordUnitaryWitness

/-- Exact unitary-orbit characterization of Born-record equality. -/
theorem recordUnitaryOrbit_iff_sameRecord
    (D : Perspective n)
    (x y : H n) :
    RecordUnitaryOrbit D x y ↔ SameRecord D x y := by
  exact projectorCommutingUnitaryOrbit_iff_sameBornRecord D x y

/-- Explicit existential form of the record-orbit theorem. -/
theorem sameRecord_iff_exists_recordUnitary
    (D : Perspective n)
    (x y : H n) :
    SameRecord D x y ↔
      ∃ U : H n ≃ₗᵢ[ℂ] H n,
        CommutesWithPerspectiveProjectors D U.toLinearEquiv.toLinearMap ∧
          U x = y := by
  exact sameBornRecord_iff_exists_projectorCommutingUnitary D x y

theorem nonempty_recordUnitaryWitness_iff_sameRecord
    (D : Perspective n)
    (x y : H n) :
    Nonempty (RecordUnitaryWitness D x y) ↔ SameRecord D x y := by
  constructor
  · rintro ⟨W⟩
    exact W.sameRecord
  · intro hRecord
    obtain ⟨U, hCommutes, hMap⟩ :=
      (sameRecord_iff_exists_recordUnitary D x y).1 hRecord
    exact ⟨{ unitary := U, commutes := hCommutes, maps_state := hMap }⟩

theorem recordUnitaryOrbit_refl
    (D : Perspective n)
    (x : H n) :
    RecordUnitaryOrbit D x x :=
  ProjectorCommutingUnitaryOrbit.refl D x

theorem recordUnitaryOrbit_symm
    {D : Perspective n}
    {x y : H n}
    (h : RecordUnitaryOrbit D x y) :
    RecordUnitaryOrbit D y x :=
  h.symm

theorem recordUnitaryOrbit_trans
    {D : Perspective n}
    {x y z : H n}
    (hxy : RecordUnitaryOrbit D x y)
    (hyz : RecordUnitaryOrbit D y z) :
    RecordUnitaryOrbit D x z :=
  hxy.trans hyz

/-- States in the same record-unitary orbit agree on every Born expectation
over the record perspective. -/
theorem bornExpectation_eq_of_recordUnitaryOrbit
    {D : Perspective n}
    {x y : H n}
    (h : RecordUnitaryOrbit D x y)
    (a : EverettianProbability.Core.Act n) :
    EverettianProbability.Refinement.bornExpectation x D a =
      EverettianProbability.Refinement.bornExpectation y D a := by
  exact bornExpectation_eq_of_projectorCommutingUnitaryOrbit h a

end
end EverettianProbability.ExactFinite
