import EverettianProbability.BornCalibration.BornExpectation
import EverettianProbability.BornCalibration.NonCircularity
import EverettianProbability.BornCalibration.Nonvacuity
import EverettianProbability.Core.Interface
import EverettianProbability.Refinement.Nonvacuity
import EverettianProbability.Refinement.NonTriviality
import EverettianProbability.Refinement.GlobalPayoffVacuity
import EverettianProbability.Preference.Nonvacuity
import EverettianProbability.Preference.NonTriviality
import EverettianProbability.Rivals.NaiveBranchCounting
import EverettianProbability.Rivals.FourthPowerWeight
import EverettianProbability.Rivals.Nonvacuity
import EverettianProbability.PhysicalRefinement.RecordNeutralWitness
import EverettianProbability.PhysicalRefinement.Nonvacuity
import EverettianProbability.PhysicalRefinement.NonTriviality
import EverettianProbability.EffectCalibration.EstimationRulePackaging
import EverettianProbability.EffectCalibration.EffectBornExpectation
import EverettianProbability.EffectCalibration.QubitWitness
import EverettianProbability.EffectCalibration.Nonvacuity
import EverettianProbability.EffectCalibration.NonTriviality
import EverettianProbability.Diachronic.Conditioning
import EverettianProbability.Diachronic.NonTriviality
import EverettianProbability.SelfLocation.RecordConditionedCredence
import EverettianProbability.SelfLocation.CredenceUniqueness
import EverettianProbability.SelfLocation.RecordRestrictionIndifference
import EverettianProbability.SelfLocation.UniformCredenceRival
import EverettianProbability.SelfLocation.UniformCredenceRefinementFailure
import EverettianProbability.SelfLocation.DecisionCredenceBridge
import EverettianProbability.Diachronic.ContinuatorCredence
import EverettianProbability.Diachronic.FutureActTotalExpectation
import EverettianProbability.Diachronic.TowerProperty
import EverettianProbability.Diachronic.ThreeLevelTowerWitness
import EverettianProbability.Diachronic.ProjectiveBornContinuators
import EverettianProbability.Diachronic.RecordNeutralPhysicalContinuation
import EverettianProbability.Diachronic.UniformRecordRespectingContinuation
import EverettianProbability.Diachronic.UniformContinuationComposition
import EverettianProbability.Diachronic.UniformContinuationAssociativity
import EverettianProbability.Diachronic.PhysicalBornRatioComposition
import EverettianProbability.Diachronic.ProjectorCommutingContinuation
import EverettianProbability.Diachronic.PhysicalPayoffInvariance
import EverettianProbability.Diachronic.RecordWeightEquivalence
import EverettianProbability.Diachronic.CellwiseOrbitPreparation
import EverettianProbability.Diachronic.EqualNormLocalUnitary
import EverettianProbability.Diachronic.BlockDiagonalRecordOrbit
import EverettianProbability.Diachronic.UnitaryRecordOrbit
import EverettianProbability.Diachronic.FineBornWeightRealization
import EverettianProbability.Diachronic.PhysicalFinePlanContinuation
import EverettianProbability.API.ExactFinitePhysicalRichness
import EverettianProbability.Frequency.HammingCells
import EverettianProbability.Frequency.HammingCounting
import EverettianProbability.Frequency.RepetitionVector
import EverettianProbability.Frequency.CellProjection
import EverettianProbability.Frequency.Distribution
import EverettianProbability.Frequency.Moments
import EverettianProbability.Frequency.Concentration
import EverettianProbability.Frequency.Typicality
import EverettianProbability.Frequency.AsymptoticTypicality
import EverettianProbability.Confirmation.FiniteBayes
import EverettianProbability.Confirmation.FrequencyModel
import EverettianProbability.Confirmation.PosteriorOdds
import EverettianProbability.Confirmation.HypothesisComparison
import EverettianProbability.Confirmation.RationalWitness
import EverettianProbability.Confirmation.SequentialUpdate
import EverettianProbability.Confirmation.FiniteObservationBatch
import EverettianProbability.Confirmation.IteratedUpdate
import EverettianProbability.Confirmation.BatchPosteriorOdds
import EverettianProbability.Confirmation.FrequencyBatchOdds
import EverettianProbability.Confirmation.RationalBatchWitness

/-!
**FR.** # Audit des axiomes — résultats principaux

Un `#print axioms` par déclaration publique majeure, à enrichir au fil des
jalons (voir `docs/THEOREM_MAP.md`). Les déclarations construites sans
but ouvert ne doivent dépendre que de `propext`, `Classical.choice`,
`Quot.sound` (la même signature que l'amont, `Gleason.gleason` inclus) ;
celles qui citent une spécification encore ouverte en amont (directement
ou transitivement) doivent, elles, révéler `sorryAx` — c'est attendu et
documente précisément la dette de ce jalon, en miroir de `SORRY_BUDGET` et
`MILESTONES.md`.

**EN.** # Axiom audit — main results

One `#print axioms` per major public declaration, to be extended milestone
by milestone (see `docs/THEOREM_MAP.md`). Declarations built with no goal
left open must depend only on `propext`, `Classical.choice`, `Quot.sound`
(the same signature as upstream, `Gleason.gleason` included); those that
cite a still-open upstream specification (directly or transitively)
must, conversely, reveal `sorryAx` — this is expected, and it documents
precisely this milestone's debt, mirroring `SORRY_BUDGET` and
`MILESTONES.md`.
-/

namespace EverettianProbability.Audit

open EverettianProbability.Core EverettianProbability.Refinement
open EverettianProbability.Preference EverettianProbability.BornCalibration
open EverettianProbability.Rivals EverettianProbability.PhysicalRefinement

-- No-open-goal declarations: must show only propext / Classical.choice / Quot.sound.
#print axioms pullbackAct_const
#print axioms pullbackAct_agree_of_agree
#print axioms const_payoffEquivalentAt
#print axioms bornExpectation_pullback_eq
#print axioms bornExpectation_refinementInvariant
#print axioms bornExpectation_refinementInvariantLocal
#print axioms uniform_not_refinementInvariantLocal
#print axioms refinementInvariantLocal_iff_pullback
#print axioms globallyPayoffPreserving_const
#print axioms not_globallyPayoffPreserving_indicator
#print axioms globalPremise_vacuous
#print axioms uniformExpectationFamily_globalPremise_vacuous
#print axioms uniformExpectationFamily
#print axioms represents
#print axioms weights_unique_on_cells
#print axioms naiveCounting_axPos
#print axioms EverettianProbability.Abstract.expectation_refinementInvariant
#print axioms EverettianProbability.Abstract.Projective.born_refinementInvariant
#print axioms EverettianProbability.Abstract.Effects.pureState_refinementInvariant
#print axioms refinement_invariant_implies_grain
#print axioms refinementInvariantLocal_iff_axGrain
#print axioms born_expectation_of_invariance
#print axioms born_expectation_formula
#print axioms naiveCounting_violates_grain
#print axioms fourthPowerWeight_axPos
#print axioms fourthPowerWeight_coarse_sum
#print axioms fourthPowerWeight_not_axNorm
#print axioms perspective_two_cases
#print axioms skewWeight_axPos
#print axioms skewWeight_axNul
#print axioms skewWeight_axNorm
#print axioms skewWeight_axGrain
#print axioms grain_does_not_imply_born_at_two
#print axioms maxExpectation_monotone
#print axioms maxExpectation_normalized_const
#print axioms maxExpectation_not_affine
#print axioms recordNeutral_refines
#print axioms recordNeutral_record_eq
#print axioms recordNeutral_payoff_eq
#print axioms recordNeutral_bornWeight_eq
#print axioms refinementNotInRecordAlgebra_holds
#print axioms born_insensitive_to_recordNeutral_refinement
#print axioms born_determined_by_accessible_record
#print axioms counting_sensitive_to_recordNeutral_refinement
#print axioms counting_underdetermined_by_accessible_record

-- Abstract lift (route qubit) and its EffectCalibration instantiation.
-- Fully qualified: several names collide with their concrete counterparts
-- already opened above (represents, canonicalWeight_axPos/axNorm,
-- RefinementInvariantLocal, refinementInvariantLocal_iff_pullback).
#print axioms EverettianProbability.Abstract.Act.agreeOn_refl
#print axioms EverettianProbability.Abstract.Act.agreeOn_symm
#print axioms EverettianProbability.Abstract.Act.agreeOn_trans
#print axioms EverettianProbability.Abstract.Act.indicator_self
#print axioms EverettianProbability.Abstract.Act.indicator_of_ne
#print axioms EverettianProbability.Abstract.Act.agreeOn_indicatorExpansion
#print axioms EverettianProbability.Abstract.V_congr_of_agreeOn
#print axioms EverettianProbability.Abstract.represents
#print axioms EverettianProbability.Abstract.weights_unique_on_cells
#print axioms EverettianProbability.Abstract.canonicalWeight_axPos
#print axioms EverettianProbability.Abstract.canonicalWeight_axNorm
#print axioms EverettianProbability.Abstract.refinementInvariantLocal_iff_pullback
#print axioms EverettianProbability.Abstract.canonicalWeight_grain
#print axioms EverettianProbability.Abstract.outcome_injective_effects
#print axioms EverettianProbability.Abstract.canonicalWeight_familyOfEstimationRule
#print axioms EverettianProbability.Abstract.effectExpectation_represents
#print axioms EverettianProbability.Abstract.effectWeight_eq_born_of_invariance
#print axioms EverettianProbability.Abstract.spinState_norm
#print axioms EverettianProbability.Abstract.spinLine_ne_bot
#print axioms EverettianProbability.Abstract.spinLine_ne_top
#print axioms EverettianProbability.Abstract.spinLine_weight
#print axioms EverettianProbability.Abstract.spinPerspective_effect_zero
#print axioms EverettianProbability.Abstract.F0_refinementInvariantLocal
#print axioms EverettianProbability.Abstract.F0_contextualNullSupport
#print axioms EverettianProbability.Abstract.spinUp_weight_eq_born
#print axioms EverettianProbability.Abstract.rationalExpectationFamily_effects_nonvacuous
#print axioms EverettianProbability.Abstract.refinementInvariantLocal_effects_nonvacuous
#print axioms EverettianProbability.Abstract.effectPerspective_outcomes_pos
#print axioms EverettianProbability.Abstract.pullbackAct_effects_apply
#print axioms EverettianProbability.Abstract.effectUniformCredence_coarse
#print axioms EverettianProbability.Abstract.effectUniformCredence_fine
#print axioms EverettianProbability.Abstract.effectUniform_not_refinementInvariantLocal

-- Static conditioning under refinement (P8): no record or temporal dynamics.
#print axioms EverettianProbability.Abstract.conditionalWeight_zero_of_not_in_fiber
#print axioms EverettianProbability.Abstract.conditionalWeight_nonneg
#print axioms EverettianProbability.Abstract.conditionalWeight_sum_eq_zero_or_one
#print axioms EverettianProbability.Abstract.conditionalWeight_normalized
#print axioms EverettianProbability.Abstract.conditionalExpectation_pullback_eq_of_weight_ne_zero
#print axioms EverettianProbability.Abstract.conditionalExpectation_total
#print axioms EverettianProbability.Abstract.conditionalWeight_trans_fiber
#print axioms EverettianProbability.Diachronic.uniformProjectiveExpectationFamily
#print axioms EverettianProbability.Diachronic.uniform_conditionalWeight_trans_fiber_lhs
#print axioms EverettianProbability.Diachronic.uniform_conditionalWeight_trans_fiber_rhs
#print axioms EverettianProbability.Diachronic.uniform_conditionalWeight_trans_fiber_fails

#print axioms EverettianProbability.Abstract.recordCompatibleMass_nonneg
#print axioms EverettianProbability.Abstract.recordConditionedCredence_zero_of_not_mem
#print axioms EverettianProbability.Abstract.recordConditionedCredence_nonneg
#print axioms EverettianProbability.Abstract.sum_recordConditionedCredence_eq_zero_or_one
#print axioms EverettianProbability.Abstract.recordConditionedCredence_normalized
#print axioms EverettianProbability.Abstract.recordCompatibleMass_univ
#print axioms EverettianProbability.Abstract.recordConditionedCredence_univ
#print axioms EverettianProbability.Abstract.recordCompatibleMass_pullback
#print axioms EverettianProbability.Abstract.recordConditionedCredence_refinement_fiber

#print axioms EverettianProbability.Abstract.canonicalRecordCredenceFamily_normalized
#print axioms EverettianProbability.Abstract.canonicalRecordCredenceFamily_agrees_unrestricted
#print axioms EverettianProbability.Abstract.canonicalRecordCredenceFamily_proportional
#print axioms EverettianProbability.Abstract.canonicalRecordCredenceFamily_refinementCoherent
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.credence_eq_recordConditionedCredence
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.refinementCoherent_of_normalized_of_proportional

#print axioms EverettianProbability.Abstract.RecordCredenceFamily.canonicalRecordCredenceFamily_oddsInvariantUnderRecordRestriction
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.canonicallyProportionalOnRecords_of_agrees_unrestricted_of_oddsInvariant
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.credence_eq_recordConditionedCredence_of_normalized_of_agrees_unrestricted_of_oddsInvariant
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.refinementCoherent_of_normalized_of_agrees_unrestricted_of_oddsInvariant
#print axioms EverettianProbability.Abstract.uniformRecordCredenceFamily_equal_on_compatible
#print axioms EverettianProbability.Abstract.sum_uniformRecordCredenceFamily_eq_one_of_nonempty
#print axioms EverettianProbability.Abstract.uniformRecordCredenceFamily_normalized
#print axioms EverettianProbability.Abstract.uniformRecordCredenceFamily_oddsInvariantUnderRecordRestriction
#print axioms EverettianProbability.Abstract.uniformRecordCredenceFamily_not_agrees_unrestricted_of_canonicalWeight_ne
#print axioms EverettianProbability.Abstract.normalized_and_oddsInvariant_do_not_imply_agrees_unrestricted
#print axioms EverettianProbability.Abstract.unrestricted_agreement_is_independent_of_normalization_and_oddsInvariant
#print axioms EverettianProbability.Abstract.projectiveExampleFine_complementFiber_card
#print axioms EverettianProbability.Abstract.uniformRecordCredence_projectiveCoarse_complement_eq
#print axioms EverettianProbability.Abstract.uniformRecordCredence_projectiveFine_complementFiber_eq
#print axioms EverettianProbability.Abstract.uniformRecordCredence_projective_refinement_failure
#print axioms EverettianProbability.Abstract.uniformRecordCredenceFamily_not_refinementCoherent_on_projectiveExample
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.agreesOnUnrestrictedRecord_of_representsUnrestrictedDecisionValue
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.representsUnrestrictedDecisionValue_of_agreesOnUnrestrictedRecord
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.representsUnrestrictedDecisionValue_iff_agreesOnUnrestrictedRecord
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.canonicalRecordCredenceFamily_representsUnrestrictedDecisionValue
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.credence_eq_indicatorDecisionValue_of_representsUnrestrictedDecisionValue
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.uniformRecordCredenceFamily_not_representsUnrestrictedDecisionValue_of_canonicalWeight_ne
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.credence_eq_recordConditionedCredence_of_normalized_of_decisionRepresentation_of_oddsInvariant
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.refinementCoherent_of_normalized_of_decisionRepresentation_of_oddsInvariant
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorCells_trans
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorMass_eq_presentWeight
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorCredence_eq_conditionalWeight
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorCredence_nonneg
#print axioms EverettianProbability.Abstract.ContinuationStep.sum_continuatorCredence_eq_one
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorCredence_trans_fiber
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.credence_on_continuators_eq
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.credence_on_continuators_trans_fiber
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorCredence_eq_conditionalWeight_total
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorExpectedValue_eq_conditionalExpectation
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorExpectedValue_const
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorExpectedValue_indicator
#print axioms EverettianProbability.Abstract.ContinuationStep.canonicalWeight_mul_conditionalWeight
#print axioms EverettianProbability.Abstract.ContinuationStep.sum_presentWeight_mul_conditionalWeight_eq_futureWeight
#print axioms EverettianProbability.Abstract.ContinuationStep.futureDecisionValue_eq_sum_presentWeight_mul_continuatorExpectedValue
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.credenceExpectedFutureValue_eq_continuatorExpectedValue
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.futureDecisionValue_eq_sum_presentWeight_mul_credenceExpectedFutureValue
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorCredence_eq_zero_of_futureWeight_eq_zero
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorCredence_zero_of_parent_ne
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorCredence_chain_rule_at_parent
#print axioms EverettianProbability.Abstract.ContinuationStep.sum_intermediateCredence_mul_laterCredence_eq_composite
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorExpectedValue_tower
#print axioms EverettianProbability.Abstract.ContinuationStep.continuatorExpectedValue_indicator_tower
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.stagedCredenceExpectedFutureValue_eq_stagedContinuatorExpectedValue
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.credenceExpectedFutureValue_tower
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.futureDecisionValue_eq_sum_presentWeight_mul_stagedCredenceExpectedFutureValue
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.weight_grain
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.refinementInvariantLocal
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.canonicalWeight_eq_explicitWeight
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.middleLeftCredence_eq_one_third
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.middleRightCredence_eq_two_thirds
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.leftConditionalExpectedValue_eq_three
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.rightConditionalExpectedValue_eq_three_halves
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.directConditionalExpectedValue_eq_two
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.stagedConditionalExpectedValue_eq_two
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.towerProperty_exact_witness
#print axioms EverettianProbability.Abstract.projectiveRefinementInvariantLocal_toConcrete
#print axioms EverettianProbability.Abstract.projectiveCanonicalWeight_eq_concreteCanonicalWeight
#print axioms EverettianProbability.Abstract.projectiveCanonicalWeight_eq_born
#print axioms EverettianProbability.Abstract.ContinuationStep.projectiveContinuatorCredence_eq_bornRatio
#print axioms EverettianProbability.Abstract.ContinuationStep.projectiveContinuatorExpectedValue_eq_born
#print axioms EverettianProbability.Abstract.ContinuationStep.projectiveFutureDecisionValue_eq_bornTotalExpectation
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.projectiveCredence_on_continuators_eq_bornRatio
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.projectiveCredenceExpectedFutureValue_eq_born
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.projectiveFutureDecisionValue_eq_bornTotalExpectation
#print axioms EverettianProbability.Abstract.RecordRespectingProjectiveContinuation.after_normalized
#print axioms EverettianProbability.Abstract.recordNeutral_parent_anc0
#print axioms EverettianProbability.Abstract.recordNeutral_parent_anc1
#print axioms EverettianProbability.Abstract.recordNeutralPhysicalContinuation_after_normalized
#print axioms EverettianProbability.Abstract.recordNeutralContinuation_refinementHiddenFromRecord
#print axioms EverettianProbability.Abstract.recordNeutral_anc0ContinuatorCredence_eq_nine_twenty_fifths
#print axioms EverettianProbability.Abstract.recordNeutral_anc1ContinuatorCredence_eq_sixteen_twenty_fifths
#print axioms EverettianProbability.Abstract.recordNeutral_label0ContinuatorCredence_eq_zero
#print axioms EverettianProbability.Abstract.recordNeutral_splitCredence_eq_one
#print axioms EverettianProbability.Abstract.recordNeutral_anc1IndicatorExpectedValue_eq_sixteen_twenty_fifths
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.recordNeutral_admissibleCredence_anc0_eq_nine_twenty_fifths
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.recordNeutral_admissibleCredence_anc1_eq_sixteen_twenty_fifths
#print axioms EverettianProbability.Abstract.recordNeutralPhysicalContinuation_integratedWitness
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.atState_after_normalized
#print axioms EverettianProbability.Abstract.coarse_weight_sum_general
#print axioms EverettianProbability.Abstract.inner_b0_coupleU
#print axioms EverettianProbability.Abstract.coupleU_preserves_label0_bornWeight
#print axioms EverettianProbability.Abstract.coupleU_preserves_label1Space_bornWeight
#print axioms EverettianProbability.Abstract.coupleU_preserves_coarseCell_bornWeight
#print axioms EverettianProbability.Abstract.accessibleRecord_coupleU
#print axioms EverettianProbability.Abstract.accessibleRecord_psiBefore_psiAfter_from_uniform
#print axioms EverettianProbability.Abstract.recordNeutralPhysicalContinuationAt_after_normalized
#print axioms EverettianProbability.Abstract.recordNeutralPhysicalContinuationAt_psiBefore_stateAfter
#print axioms EverettianProbability.Abstract.recordNeutralContinuatorCredence_eq_bornRatio_before
#print axioms EverettianProbability.Abstract.recordNeutralContinuatorExpectedValue_eq_born_before
#print axioms EverettianProbability.Abstract.RecordCredenceFamily.recordNeutralAdmissibleCredence_eq_bornRatio_before
#print axioms EverettianProbability.Abstract.recordNeutralUniformPhysicalContinuation_integratedWitness
#print axioms EverettianProbability.Abstract.preservesRecordObservable_id
#print axioms EverettianProbability.Abstract.PreservesRecordObservable.comp
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.identity_record_preserved
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.preserves_coarseBornWeight_of_preserves_fineBornWeight
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_isometry
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_record_preserved
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_presentBornWeight_preserved
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_atState_after_normalized
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.identity_trans_evolution
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_identity_evolution
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralWithFutureIdentity_evolution
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralWithPresentIdentity_evolution
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralUniformContinuation_identityClosureWitness
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.EvolutionEquivalent.refl
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.EvolutionEquivalent.symm
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.EvolutionEquivalent.trans
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.finalBornWeight_eq_of_evolutionEquivalent
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.atState_stateAfter_eq_of_evolutionEquivalent
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.evolved_normalized
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.laterPair_preserves_earliestRecord
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_associative_evolutionEquivalent
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_associative_atState
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_atState_eq_later_atEvolvedState
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.identity_trans_evolutionEquivalent
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_identity_evolutionEquivalent
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralThreeStageLeft_evolution
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralThreeStageRight_evolution
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralThreeStage_associativityWitness
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.physicalContinuatorBornRatio_zero_of_parent_ne
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.continuatorCredence_eq_physicalContinuatorBornRatio
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.physicalContinuatorBornRatio_chain_at_parent
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.sum_intermediatePhysicalBornRatio_eq_composite
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.trans_associated_parentCell_eq
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.physicalContinuatorBornRatio_associative
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.continuatorCredence_associative_physical
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.physicalContinuatorBornRatio_threeStage_product
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.physicalContinuatorBornRatio_threeStage_product_left
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralThreeStageLeft_anc1PhysicalBornRatio_eq
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralThreeStageRight_anc1PhysicalBornRatio_eq
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.recordNeutralThreeStage_physicalBornRatioWitness
#print axioms EverettianProbability.Abstract.commutesWithProjector_id
#print axioms EverettianProbability.Abstract.CommutesWithProjector.comp
#print axioms EverettianProbability.Abstract.commutesWithPerspectiveProjectors_id
#print axioms EverettianProbability.Abstract.CommutesWithPerspectiveProjectors.comp
#print axioms EverettianProbability.Abstract.CommutesWithProjector.orthogonalComplement
#print axioms EverettianProbability.Abstract.bornWeight_preserved_of_commutesWithProjector
#print axioms EverettianProbability.Abstract.presentBornWeight_preserved_of_commutesWithPerspectiveProjectors
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.presentBornWeight_preserved
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.toUniform_presentBornWeight_preserved
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.continuatorCredence_eq_physicalBornRatio
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.coupleU_b0
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.coupleU_commutes_label0Line
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.coupleU_commutes_label1Space
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.coupleU_commutes_coarsePerspectiveProjectors
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutralUniformFromProjectorCommutation_evolutionEquivalent
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutralProjectorCommuting_anc0PhysicalBornRatio_eq
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutralProjectorCommuting_anc1PhysicalBornRatio_eq
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutralProjectorCommuting_anc1Credence_eq
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutralProjectorCommutation_integratedWitness
#print axioms EverettianProbability.Abstract.preservesBornExpectationOnPerspective_id
#print axioms EverettianProbability.Abstract.PreservesBornExpectationOnPerspective.comp
#print axioms EverettianProbability.Abstract.bornExpectation_congr_of_agreeOn
#print axioms EverettianProbability.Abstract.preservesBornExpectation_of_preservesCellBornWeights
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.preservesBornExpectation_present
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.physicalBornExpectation_pullback_eq
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.physicalBornExpectation_eq_of_payoffEquivalent
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.realizesBornPayoffInvariance
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.preservesBornExpectation_present
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.physicalBornExpectation_pullback_eq
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.physicalBornExpectation_eq_of_payoffEquivalent
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.realizesBornPayoffInvariance
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_realizesBornPayoffInvariance
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_bornExpectation_pullback_eq_all_states
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_bornExpectation_eq_of_payoffEquivalent
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_payoff_invariant_all_states
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_payoffExpectation_before_eq_sixteen_twenty_fifths
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_payoffExpectation_after_eq_sixteen_twenty_fifths
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_payoff_nonconstant
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutralPhysicalPayoffInvariance_integratedWitness
#print axioms EverettianProbability.Abstract.sameBornRecord_iff_bornRecord_eq
#print axioms EverettianProbability.Abstract.SameBornRecord.refl
#print axioms EverettianProbability.Abstract.SameBornRecord.symm
#print axioms EverettianProbability.Abstract.SameBornRecord.trans
#print axioms EverettianProbability.Abstract.bornExpectation_indicator_cell
#print axioms EverettianProbability.Abstract.bornExpectation_eq_of_sameBornRecord
#print axioms EverettianProbability.Abstract.sameBornRecord_of_bornExpectation_eq_all
#print axioms EverettianProbability.Abstract.sameBornRecord_iff_bornExpectation_eq_all
#print axioms EverettianProbability.Abstract.sameBornRecord_iff_pullbackBornExpectation_eq_all
#print axioms EverettianProbability.Abstract.bornExpectation_eq_of_sameBornRecord_and_payoffEquivalent
#print axioms EverettianProbability.Abstract.realizesBornPayoffInvariance_iff_sameBornRecord
#print axioms EverettianProbability.Abstract.UniformRecordRespectingProjectiveContinuation.sameBornRecord_before_after
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.sameBornRecord_before_after
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_psiBefore_ne_psiAfter
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_psiBefore_psiAfter_sameBornRecord
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_allCoarseBornExpectations_eq
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutral_allPullbackBornExpectations_eq
#print axioms EverettianProbability.Abstract.ProjectorCommutingProjectiveContinuation.recordNeutralRecordWeightEquivalence_integratedWitness
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.towerProperty_exact_witness_from_general_theorem
#print axioms EverettianProbability.Abstract.ThreeLevelTowerWitness.towerProperty_witness_nontrivial
#print axioms EverettianProbability.Abstract.cellComponent_mem
#print axioms EverettianProbability.Abstract.cellComponent_norm_sq
#print axioms EverettianProbability.Abstract.cellComponents_inner_eq_zero
#print axioms EverettianProbability.Abstract.cellComponents_pairwise_inner_eq_zero
#print axioms EverettianProbability.Abstract.sum_cellComponents_eq
#print axioms EverettianProbability.Abstract.sameBornRecord_iff_cellComponent_norm_sq_eq
#print axioms EverettianProbability.Abstract.sameBornRecord_cellComponent_norm_eq
#print axioms EverettianProbability.Abstract.sameBornRecord_of_cellComponent_norm_eq
#print axioms EverettianProbability.Abstract.sameBornRecord_iff_cellComponent_norm_eq
#print axioms EverettianProbability.Abstract.sameBornRecord_cellComponent_zero_iff
#print axioms EverettianProbability.Abstract.cellwiseEqualNormData_of_sameBornRecord
#print axioms EverettianProbability.Abstract.ProjectorCommutingIsometricOrbit.refl
#print axioms EverettianProbability.Abstract.ProjectorCommutingIsometricOrbit.trans
#print axioms EverettianProbability.Abstract.sameBornRecord_of_projectorCommutingIsometricOrbit
#print axioms EverettianProbability.Abstract.cellComponent_map_of_commutes_and_maps
#print axioms EverettianProbability.Abstract.maps_state_of_maps_all_cellComponents
#print axioms EverettianProbability.Abstract.maps_state_iff_maps_all_cellComponents
#print axioms EverettianProbability.Abstract.recordNeutral_projectorCommutingIsometricOrbit
#print axioms EverettianProbability.Abstract.recordNeutralCellwiseOrbitPreparation_integratedWitness
#print axioms EverettianProbability.Abstract.EqualNormUnitaryWitness.norm_eq
#print axioms EverettianProbability.Abstract.EqualNormUnitaryWitness.refl
#print axioms EverettianProbability.Abstract.EqualNormUnitaryWitness.symm
#print axioms EverettianProbability.Abstract.EqualNormUnitaryWitness.trans
#print axioms EverettianProbability.Abstract.exists_equalNormUnitaryWitness
#print axioms EverettianProbability.Abstract.exists_linearIsometryEquiv_apply_eq_of_norm_eq
#print axioms EverettianProbability.Abstract.nonempty_equalNormUnitaryWitness_iff
#print axioms EverettianProbability.Abstract.sourceCellVector_norm_eq_targetCellVector
#print axioms EverettianProbability.Abstract.localCellUnitary_map_source
#print axioms EverettianProbability.Abstract.localCellUnitary_norm_map
#print axioms EverettianProbability.Abstract.CellwiseUnitaryData.local_norm_map
#print axioms EverettianProbability.Abstract.CellwiseUnitaryData.maps_component_val
#print axioms EverettianProbability.Abstract.CellwiseUnitaryData.maps_zero_source_to_zero_target
#print axioms EverettianProbability.Abstract.CellwiseUnitaryData.maps_zero_target_to_zero_source
#print axioms EverettianProbability.Abstract.sameBornRecord_of_cellwiseUnitaryData
#print axioms EverettianProbability.Abstract.nonempty_cellwiseUnitaryData_iff_sameBornRecord
#print axioms EverettianProbability.Abstract.recordNeutralCellwiseUnitaryData_maps_label0
#print axioms EverettianProbability.Abstract.recordNeutralCellwiseUnitaryData_maps_complement
#print axioms EverettianProbability.Abstract.recordNeutralEqualNormLocalUnitary_integratedWitness
#print axioms EverettianProbability.Abstract.cellProjectionToSubmodule_val
#print axioms EverettianProbability.Abstract.cellBlockLinearMap_apply
#print axioms EverettianProbability.Abstract.cellBlockLinearMap_mem
#print axioms EverettianProbability.Abstract.perspectiveCells_isOrtho
#print axioms EverettianProbability.Abstract.projL_cellBlockLinearMap_self
#print axioms EverettianProbability.Abstract.projL_cellBlockLinearMap_eq_zero_of_ne
#print axioms EverettianProbability.Abstract.projL_blockDiagonalLinearMap
#print axioms EverettianProbability.Abstract.blockDiagonalLinearMap_projL
#print axioms EverettianProbability.Abstract.blockDiagonalLinearMap_commutes
#print axioms EverettianProbability.Abstract.norm_cellBlockLinearMap
#print axioms EverettianProbability.Abstract.sum_cellComponent_norm_sq_eq_norm_sq
#print axioms EverettianProbability.Abstract.blockDiagonalLinearMap_norm_sq
#print axioms EverettianProbability.Abstract.blockDiagonalLinearMap_isometry
#print axioms EverettianProbability.Abstract.blockDiagonalLinearMap_maps_cellComponent
#print axioms EverettianProbability.Abstract.blockDiagonalLinearMap_maps_state
#print axioms EverettianProbability.Abstract.projectorCommutingIsometricOrbit_of_sameBornRecord
#print axioms EverettianProbability.Abstract.projectorCommutingIsometricOrbit_iff_sameBornRecord
#print axioms EverettianProbability.Abstract.sameBornRecord_iff_exists_projectorCommutingIsometry
#print axioms EverettianProbability.Abstract.recordNeutralAssembledBlockEvolution_isometry
#print axioms EverettianProbability.Abstract.recordNeutralAssembledBlockEvolution_commutes
#print axioms EverettianProbability.Abstract.recordNeutralAssembledBlockEvolution_maps_state
#print axioms EverettianProbability.Abstract.recordNeutralBlockDiagonalRecordOrbit_integratedWitness
#print axioms EverettianProbability.Abstract.linearIsometryOfNormPreserving_injective
#print axioms EverettianProbability.Abstract.normPreservingLinearMap_surjective
#print axioms EverettianProbability.Abstract.linearIsometryEquivOfNormPreserving_apply
#print axioms EverettianProbability.Abstract.linearIsometryEquivOfNormPreserving_toLinearMap
#print axioms EverettianProbability.Abstract.blockDiagonalLinearIsometry_surjective
#print axioms EverettianProbability.Abstract.blockDiagonalUnitary_apply
#print axioms EverettianProbability.Abstract.blockDiagonalUnitary_commutes
#print axioms EverettianProbability.Abstract.blockDiagonalUnitary_maps_state
#print axioms EverettianProbability.Abstract.LinearIsometryEquiv.commutesWithProjector_symm
#print axioms EverettianProbability.Abstract.LinearIsometryEquiv.commutesWithPerspectiveProjectors_symm
#print axioms EverettianProbability.Abstract.blockDiagonalUnitary_symm_commutes
#print axioms EverettianProbability.Abstract.blockDiagonalUnitary_symm_maps_state
#print axioms EverettianProbability.Abstract.ProjectorCommutingUnitaryOrbit.refl
#print axioms EverettianProbability.Abstract.ProjectorCommutingUnitaryOrbit.symm
#print axioms EverettianProbability.Abstract.ProjectorCommutingUnitaryOrbit.trans
#print axioms EverettianProbability.Abstract.projectorCommutingIsometricOrbit_of_unitaryOrbit
#print axioms EverettianProbability.Abstract.projectorCommutingUnitaryOrbit_of_isometricOrbit
#print axioms EverettianProbability.Abstract.projectorCommutingUnitaryOrbit_iff_isometricOrbit
#print axioms EverettianProbability.Abstract.sameBornRecord_of_projectorCommutingUnitaryOrbit
#print axioms EverettianProbability.Abstract.projectorCommutingUnitaryOrbit_of_sameBornRecord
#print axioms EverettianProbability.Abstract.projectorCommutingUnitaryOrbit_iff_sameBornRecord
#print axioms EverettianProbability.Abstract.sameBornRecord_iff_exists_projectorCommutingUnitary
#print axioms EverettianProbability.Abstract.bornExpectation_eq_of_projectorCommutingUnitaryOrbit
#print axioms EverettianProbability.Abstract.recordNeutralAssembledBlockUnitary_maps_state
#print axioms EverettianProbability.Abstract.recordNeutralAssembledBlockUnitary_symm_maps_state
#print axioms EverettianProbability.Abstract.recordNeutralAssembledBlockUnitary_commutes
#print axioms EverettianProbability.Abstract.recordNeutralAssembledBlockUnitary_symm_commutes
#print axioms EverettianProbability.Abstract.recordNeutral_projectorCommutingUnitaryOrbit
#print axioms EverettianProbability.Abstract.recordNeutralUnitaryRecordOrbit_integratedWitness
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.perspectiveCell_ne_bot
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.exists_unitVector_in_perspectiveCell
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.chosenFutureUnitVector_norm
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.fineTargetComponent_mem
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.fineTargetComponent_norm_sq
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.fineTargetComponents_inner_eq_zero
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.projL_fineWeightTargetState
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.fineWeightTargetState_bornWeight
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.fineWeightTargetState_fibre_sum
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.fineWeightTargetState_sameBornRecord
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.fineWeightTargetState_norm_eq
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.fineWeightTargetState_normalized
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.exists_projectorCommutingUnitary_realizing_fineBornWeightPlan
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.exists_state_and_unitary_realizing_fineBornWeightPlan
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.ofTargetState_weight
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFineBornWeightPlan_label0
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFineBornWeightPlan_anc0
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFineBornWeightPlan_anc1
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFineWeightTarget_normalized
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.exists_recordNeutralFineWeightRealizingUnitary
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFineBornWeightRealization_integratedWitness

#print axioms EverettianProbability.Abstract.FineBornWeightPlan.conditionalRatio_nonneg
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.conditionalRatio_zero_of_parent_ne
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.sum_conditionalRatio_eq_one
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingUnitary_commutes
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingUnitary_maps_state
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingUnitary_bornWeight
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingEvolution_isometry
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingEvolution_preserves_bornRecord
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingProjectorCommutingContinuation_presentBornWeight_preserved
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingUniformContinuation_evolution_at_source
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingUniformContinuation_record_preserved
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingUniformContinuation_futureBornWeight
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingContinuationAt_stateAfter
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.physicalContinuatorBornRatio_eq_conditionalRatio
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.continuatorCredence_eq_conditionalRatio
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.sum_realizedContinuatorCredence_eq_one
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizedContinuatorCredence_zero_of_parent_ne
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.presentBornWeight_mul_continuatorCredence_eq_planWeight
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingContinuation_bornExpectation_pullback_eq
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.realizingContinuation_realizesBornPayoffInvariance
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.exists_uniformContinuation_realizing_plan
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.exactFinitePhysicalFinePlanRealization
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFinePlan_anc0PhysicalRatio_eq
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFinePlan_anc1PhysicalRatio_eq
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFinePlan_anc0Credence_eq
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralFinePlan_anc1Credence_eq
#print axioms EverettianProbability.Abstract.FineBornWeightPlan.recordNeutralPhysicalFinePlanContinuation_integratedWitness

#print axioms EverettianProbability.API.CompatibleFineBornWeights.nonneg
#print axioms EverettianProbability.API.CompatibleFineBornWeights.fibre_sum
#print axioms EverettianProbability.API.fineBornWeightPlanOfCompatible_weight
#print axioms EverettianProbability.API.compatibleFineBornWeights_of_plan
#print axioms EverettianProbability.API.projectorCommutingUnitaryRealizesFineWeights_of_compatible
#print axioms EverettianProbability.API.compatibleFineBornWeights_of_projectorCommutingUnitary
#print axioms EverettianProbability.API.compatibleFineBornWeights_iff_projectorCommutingUnitary
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.evolution_isometry
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.preserves_presentBornRecord
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.toUniformContinuation_realizes_weights
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.realizesBornPayoffInvariance
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.bornExpectation_pullback_eq
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.physicalContinuatorBornRatio_eq_prescribed
#print axioms EverettianProbability.API.sum_prescribedConditionalRatio_eq_one
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.continuatorCredence_eq_prescribedConditionalRatio
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.sum_continuatorCredence_eq_one
#print axioms EverettianProbability.API.ExactFinitePhysicalRealization.parentWeight_mul_continuatorCredence_eq_fineWeight
#print axioms EverettianProbability.API.compatibleFineBornWeights_iff_nonempty_exactRealization
#print axioms EverettianProbability.API.exactFinitePhysicalRichness
#print axioms EverettianProbability.API.exactFinitePhysicalRichness_calibrated
#print axioms EverettianProbability.API.recordNeutralExactFinitePhysicalRealization_anc0
#print axioms EverettianProbability.API.recordNeutralExactFinitePhysicalRealization_anc1
#print axioms EverettianProbability.API.recordNeutralExactFinitePhysicalRealization_commutes
#print axioms EverettianProbability.API.recordNeutralExactFinitePhysicalRichness_integratedWitness

#print axioms EverettianProbability.Frequency.configurationBasis_mem_frequencySitesCell
#print axioms EverettianProbability.Frequency.frequencySitesCell_ortho
#print axioms EverettianProbability.Frequency.configurationBranch_norm
#print axioms EverettianProbability.Frequency.configurationBranch_ne_zero
#print axioms EverettianProbability.Frequency.configurationBranch_inner_eq_zero_of_ne
#print axioms EverettianProbability.Frequency.configurationBranch_mem_frequencyCell
#print axioms EverettianProbability.Frequency.frequencyCell_ortho
#print axioms EverettianProbability.Frequency.frequencySitesCell_iSup
#print axioms EverettianProbability.Frequency.frequencyCell_iSup
#print axioms EverettianProbability.Frequency.hammingWeight_le
#print axioms EverettianProbability.Frequency.frequencySitesCell_eq_bot_of_lt
#print axioms EverettianProbability.Frequency.frequencyCell_eq_bot_of_lt
#print axioms EverettianProbability.Frequency.frequencySitesCell_iSup_fin
#print axioms EverettianProbability.Frequency.frequencyCell_iSup_fin
#print axioms EverettianProbability.Frequency.hammingWeight_prefixConfiguration
#print axioms EverettianProbability.Frequency.frequencyCell_ne_bot
#print axioms EverettianProbability.Frequency.frequencyCell_injective
#print axioms EverettianProbability.Frequency.frequencyPerspective
#print axioms EverettianProbability.Frequency.frequencyCell_mem_frequencyPerspective
#print axioms EverettianProbability.Frequency.frequencyPerspective_cells_card

#print axioms EverettianProbability.Frequency.repetitionSitesVector_apply
#print axioms EverettianProbability.Frequency.sitesEquivR_repetitionVector
#print axioms EverettianProbability.Frequency.repetitionAmplitude_eq_of_hammingWeight_eq
#print axioms EverettianProbability.Frequency.repetitionSitesVector_eq_of_hammingWeight_eq
#print axioms EverettianProbability.Frequency.repetitionAmplitude_prefixConfiguration
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_nonneg
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_eq_of_hammingWeight_eq
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_prefixConfiguration
#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_sum
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_eq_norm_sq_powers
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_prefix_eq_norm_sq_powers
#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_sum_norm_sq_powers

#print axioms EverettianProbability.Frequency.onesFinset_configurationOfOnes
#print axioms EverettianProbability.Frequency.configurationOfOnes_onesFinset
#print axioms EverettianProbability.Frequency.hammingWeightFiberEquiv
#print axioms EverettianProbability.Frequency.hammingWeight_fiber_card
#print axioms EverettianProbability.Frequency.configurationsOfWeight_card
#print axioms EverettianProbability.Frequency.hammingWeight_image_univ

#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_binomial_sum
#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_elementary_sum_pow
#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_one
#print axioms EverettianProbability.Frequency.repetitionVector_norm_eq_one

#print axioms EverettianProbability.Frequency.frequencySitesCell_starProjection_configurationBasis
#print axioms EverettianProbability.Frequency.frequencyCell_starProjection_configurationBranch
#print axioms EverettianProbability.Frequency.projL_frequencyCell_configurationBranch
#print axioms EverettianProbability.Frequency.repetitionFrequencySitesComponent_apply
#print axioms EverettianProbability.Frequency.repetitionFrequencySitesComponent_eq_sum
#print axioms EverettianProbability.Frequency.repetitionSitesVector_eq_sum_configurationBasis
#print axioms EverettianProbability.Frequency.frequencySitesCell_starProjection_repetitionSitesVector
#print axioms EverettianProbability.Frequency.sitesEquivR_repetitionFrequencyComponent
#print axioms EverettianProbability.Frequency.projL_frequencyCell_repetitionVector
#print axioms EverettianProbability.Frequency.repetitionFrequencyComponent_mem_frequencyCell
#print axioms EverettianProbability.Frequency.repetitionFrequencySitesComponent_norm_sq_eq_sum
#print axioms EverettianProbability.Frequency.repetitionFrequencyComponent_norm_sq_eq_sum
#print axioms EverettianProbability.Frequency.projL_frequencyCell_repetitionVector_norm_sq_eq_sum
#print axioms EverettianProbability.Frequency.sum_repetitionConfigurationWeight_configurationsOfWeight
#print axioms EverettianProbability.Frequency.repetitionFrequencySitesComponent_norm_sq_eq_binomial
#print axioms EverettianProbability.Frequency.repetitionFrequencyComponent_norm_sq_eq_binomial
#print axioms EverettianProbability.Frequency.projL_frequencyCell_repetitionVector_norm_sq_eq_binomial
#print axioms EverettianProbability.Frequency.sum_projL_frequencyCell_repetitionVector_norm_sq_eq_elementary_sum_pow
#print axioms EverettianProbability.Frequency.sum_projL_frequencyCell_repetitionVector_norm_sq_eq_one
#print axioms EverettianProbability.Frequency.sum_frequencyPerspective_repetitionVector_norm_sq_eq_elementary_sum_pow
#print axioms EverettianProbability.Frequency.sum_frequencyPerspective_repetitionVector_norm_sq_eq_one
#print axioms EverettianProbability.Frequency.frequencyMass_eq_projectiveWeight
#print axioms EverettianProbability.Frequency.frequencyMass_nonneg
#print axioms EverettianProbability.Frequency.frequencyMass_eq_binomial
#print axioms EverettianProbability.Frequency.sum_frequencyMass_eq_elementary_sum_pow
#print axioms EverettianProbability.Frequency.sum_frequencyMass_eq_one
#print axioms EverettianProbability.Frequency.frequencyMass_isProbabilityFamily
#print axioms EverettianProbability.Frequency.sum_range_cast_mul_choose_mul_powers
#print axioms EverettianProbability.Frequency.frequencyCountFirstMoment_nonneg
#print axioms EverettianProbability.Frequency.frequencyCountFirstMoment_eq_general
#print axioms EverettianProbability.Frequency.frequencyCountFirstMoment_eq
#print axioms EverettianProbability.Frequency.sum_range_cast_fallingTwo_mul_choose_mul_powers
#print axioms EverettianProbability.Frequency.frequencyCountSecondFactorialMoment_nonneg
#print axioms EverettianProbability.Frequency.frequencyCountSecondFactorialMoment_eq_general
#print axioms EverettianProbability.Frequency.frequencyCountSecondFactorialMoment_eq
#print axioms EverettianProbability.Frequency.frequencyCountSecondMoment_eq_secondFactorialMoment_add_firstMoment
#print axioms EverettianProbability.Frequency.frequencyCountSecondMoment_nonneg
#print axioms EverettianProbability.Frequency.frequencyCountSecondMoment_eq_general
#print axioms EverettianProbability.Frequency.frequencyCountSecondMoment_eq
#print axioms EverettianProbability.Frequency.frequencyCountVariance_eq
#print axioms EverettianProbability.Frequency.frequencyCountVariance_nonneg
#print axioms EverettianProbability.Frequency.frequencyRelativeFirstMoment_eq_countFirstMoment_div
#print axioms EverettianProbability.Frequency.frequencyRelativeFirstMoment_eq
#print axioms EverettianProbability.Frequency.frequencyRelativeSecondMoment_eq_countSecondMoment_div_sq
#print axioms EverettianProbability.Frequency.frequencyRelativeVariance_eq_countVariance_div_sq
#print axioms EverettianProbability.Frequency.frequencyRelativeVariance_eq
#print axioms EverettianProbability.Frequency.frequencyRelativeVariance_nonneg
#print axioms EverettianProbability.Frequency.frequencyRelativeDeviationSecondMoment_nonneg
#print axioms EverettianProbability.Frequency.frequencyRelativeDeviationSecondMoment_eq
#print axioms EverettianProbability.Frequency.frequencyRelativeDeviationSecondMoment_eq_variance
#print axioms EverettianProbability.Frequency.frequencyAtypicalMass_nonneg
#print axioms EverettianProbability.Frequency.epsilon_sq_mul_frequencyAtypicalMass_le_deviationSecondMoment
#print axioms EverettianProbability.Frequency.frequencyAtypicalMass_le_deviationSecondMoment_div
#print axioms EverettianProbability.Frequency.frequencyAtypicalMass_le_chebyshev
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_nonneg
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_add_frequencyAtypicalMass_eq_totalMass
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_add_frequencyAtypicalMass_eq_one
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_eq_one_sub_frequencyAtypicalMass
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_le_one
#print axioms EverettianProbability.Frequency.one_sub_chebyshev_le_frequencyTypicalMass
#print axioms EverettianProbability.Frequency.one_sub_delta_le_frequencyTypicalMass
#print axioms EverettianProbability.Frequency.chebyshevBound_le_delta_of_large_repetitions
#print axioms EverettianProbability.Frequency.frequencyAtypicalMass_le_delta_of_large_repetitions
#print axioms EverettianProbability.Frequency.one_sub_delta_le_frequencyTypicalMass_of_large_repetitions
#print axioms EverettianProbability.Frequency.exists_frequencyTypicality_threshold
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.evidence_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_evidence_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_posteriorWeight_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_posteriorWeight_eq_zero
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_mul_evidence
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_nonneg
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_eq_binomial
#print axioms EverettianProbability.Confirmation.sum_frequencyLikelihood_eq_one
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_evidence_eq
#print axioms EverettianProbability.Confirmation.sum_frequencyConfirmationModel_evidence_eq_one
#print axioms EverettianProbability.Confirmation.sum_frequencyConfirmationModel_posteriorWeight_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_cross_mul
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_div_posteriorWeight_eq
#print axioms EverettianProbability.Confirmation.frequencyCellKernel_nonneg
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_eq_choose_mul_kernel
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_div_eq_kernel_div
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_posteriorWeight_div_eq
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_lt_iff_jointWeight_lt
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_eq_iff_jointWeight_eq
#print axioms EverettianProbability.Confirmation.frequencyBayesFactor_nonneg
#print axioms EverettianProbability.Confirmation.one_lt_frequencyBayesFactor_iff
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_posteriorOdds_eq_priorOdds_mul_bayesFactor
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_posteriorOdds_eq_bayesFactor_of_equal_prior
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_posteriorWeight_lt_iff_kernel_lt_of_equal_prior
#print axioms EverettianProbability.Confirmation.rationalWitnessPrior_nonneg
#print axioms EverettianProbability.Confirmation.sum_rationalWitnessPrior_eq_one
#print axioms EverettianProbability.Confirmation.rationalWitnessAmplitudes_normalized
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_kernel_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_kernel_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_likelihood_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_likelihood_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_evidence_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_posteriorWeight_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_posteriorWeight_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_bayesFactor_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_posteriorOdds_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_lowPosterior_lt_highPosterior
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.twoObservationEvidence_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.twoObservationEvidence_comm
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.twoObservationPosteriorWeight_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_twoObservationPosteriorWeight_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorUpdatedModel_evidence_eq
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorUpdatedModel_posteriorWeight_eq
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sequentialPosteriorWeight_comm
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.observationLikelihoodProduct_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.observationLikelihoodProduct_reverse
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationEvidence_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationEvidence_nil
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationEvidence_singleton
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationEvidence_pair
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationEvidence_reverse
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationPosteriorWeight_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_finiteObservationPosteriorWeight_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_finiteObservationPosteriorWeight_eq_zero
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationPosteriorWeight_nil
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationPosteriorWeight_singleton
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationPosteriorWeight_pair
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationPosteriorWeight_reverse
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorUpdatedModel_finiteObservationEvidence_eq
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorUpdatedModel_finiteObservationPosteriorWeight_eq
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.SequentialUpdateWitness.finiteObservationEvidence_ne_zero
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.iteratedPosteriorModel_likelihood
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.iteratedPosteriorModel_prior_eq_finiteObservationPosteriorWeight
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.iteratedPosteriorModel_prior_reverse
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_iteratedPosteriorModel_prior_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.observationLikelihoodRatioProduct_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.observationLikelihoodProduct_ne_zero
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.observationLikelihoodProduct_div_eq_ratioProduct
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationBayesFactor_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationBayesFactor_eq_ratioProduct
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationPosteriorWeight_cross_mul
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationPosteriorOdds_eq
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.finiteObservationPosteriorOdds_eq_priorOdds_mul_ratioProduct
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.iteratedPosteriorModel_priorOdds_eq
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.iteratedPosteriorModel_priorOdds_eq_priorOdds_mul_ratioProduct
#print axioms EverettianProbability.Confirmation.frequencyKernelRatioProduct_nonneg
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_likelihoodRatioProduct_eq_kernelRatioProduct
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_ne_zero_of_kernel_ne_zero
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_likelihood_ne_zero_of_kernel_ne_zero
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_finiteObservationBayesFactor_eq_kernelRatioProduct
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_finiteObservationPosteriorOdds_eq
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_iteratedPriorOdds_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_likelihoodProduct_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_likelihoodProduct_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_kernelRatioProduct_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_kernelRatioProduct_eq_singleBayesFactors
#print axioms EverettianProbability.Confirmation.rationalWitness_batchBayesFactor_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_batchEvidence_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_batchPosteriorWeight_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_batchPosteriorWeight_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_batchPosteriorOdds_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_batchPosteriorOdds_eq_bayesFactor
#print axioms EverettianProbability.Confirmation.rationalWitness_secondEvidence_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_iteratedPrior_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_iteratedPrior_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_iteratedPriorOdds_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_iteratedPrior_lt_high

end EverettianProbability.Audit
