import EverettianProbability.BornCalibration.BornExpectation
import EverettianProbability.BornCalibration.NonCircularity
import EverettianProbability.BornCalibration.Nonvacuity
import EverettianProbability.Core.Interface
import EverettianProbability.Refinement.Nonvacuity
import EverettianProbability.Refinement.NonTriviality
import EverettianProbability.Refinement.GlobalPayoffVacuity
import EverettianProbability.Preference.Nonvacuity
import EverettianProbability.Preference.NonTriviality
import EverettianProbability.Rivals.NaiveBranchCounting
import EverettianProbability.Rivals.FourthPowerWeight
import EverettianProbability.Rivals.Nonvacuity
import EverettianProbability.PhysicalRefinement.RecordNeutralWitness
import EverettianProbability.PhysicalRefinement.Nonvacuity
import EverettianProbability.PhysicalRefinement.NonTriviality
import EverettianProbability.EffectCalibration.EstimationRulePackaging
import EverettianProbability.EffectCalibration.EffectBornExpectation
import EverettianProbability.EffectCalibration.QubitWitness
import EverettianProbability.EffectCalibration.Nonvacuity
import EverettianProbability.EffectCalibration.NonTriviality
import EverettianProbability.Diachronic.Conditioning
import EverettianProbability.Diachronic.NonTriviality
import EverettianProbability.Frequency.HammingCells
import EverettianProbability.Frequency.HammingCounting
import EverettianProbability.Frequency.RepetitionVector
import EverettianProbability.Frequency.CellProjection
import EverettianProbability.Frequency.Distribution
import EverettianProbability.Frequency.Moments
import EverettianProbability.Frequency.Concentration
import EverettianProbability.Frequency.Typicality
import EverettianProbability.Frequency.AsymptoticTypicality
import EverettianProbability.Confirmation.FiniteBayes
import EverettianProbability.Confirmation.FrequencyModel
import EverettianProbability.Confirmation.PosteriorOdds
import EverettianProbability.Confirmation.HypothesisComparison
import EverettianProbability.Confirmation.RationalWitness

/-!
**FR.** # Audit des axiomes — résultats principaux

Un `#print axioms` par déclaration publique majeure, à enrichir au fil des
jalons (voir `docs/THEOREM_MAP.md`). Les déclarations construites sans
but ouvert ne doivent dépendre que de `propext`, `Classical.choice`,
`Quot.sound` (la même signature que l'amont, `Gleason.gleason` inclus) ;
celles qui citent une spécification encore ouverte en amont (directement
ou transitivement) doivent, elles, révéler `sorryAx` — c'est attendu et
documente précisément la dette de ce jalon, en miroir de `SORRY_BUDGET` et
`MILESTONES.md`.

**EN.** # Axiom audit — main results

One `#print axioms` per major public declaration, to be extended milestone
by milestone (see `docs/THEOREM_MAP.md`). Declarations built with no goal
left open must depend only on `propext`, `Classical.choice`, `Quot.sound`
(the same signature as upstream, `Gleason.gleason` included); those that
cite a still-open upstream specification (directly or transitively)
must, conversely, reveal `sorryAx` — this is expected, and it documents
precisely this milestone's debt, mirroring `SORRY_BUDGET` and
`MILESTONES.md`.
-/

namespace EverettianProbability.Audit

open EverettianProbability.Core EverettianProbability.Refinement
open EverettianProbability.Preference EverettianProbability.BornCalibration
open EverettianProbability.Rivals EverettianProbability.PhysicalRefinement

-- No-open-goal declarations: must show only propext / Classical.choice / Quot.sound.
#print axioms pullbackAct_const
#print axioms pullbackAct_agree_of_agree
#print axioms const_payoffEquivalentAt
#print axioms bornExpectation_pullback_eq
#print axioms bornExpectation_refinementInvariant
#print axioms bornExpectation_refinementInvariantLocal
#print axioms uniform_not_refinementInvariantLocal
#print axioms refinementInvariantLocal_iff_pullback
#print axioms globallyPayoffPreserving_const
#print axioms not_globallyPayoffPreserving_indicator
#print axioms globalPremise_vacuous
#print axioms uniformExpectationFamily_globalPremise_vacuous
#print axioms uniformExpectationFamily
#print axioms represents
#print axioms weights_unique_on_cells
#print axioms naiveCounting_axPos
#print axioms EverettianProbability.Abstract.expectation_refinementInvariant
#print axioms EverettianProbability.Abstract.Projective.born_refinementInvariant
#print axioms EverettianProbability.Abstract.Effects.pureState_refinementInvariant
#print axioms refinement_invariant_implies_grain
#print axioms refinementInvariantLocal_iff_axGrain
#print axioms born_expectation_of_invariance
#print axioms born_expectation_formula
#print axioms naiveCounting_violates_grain
#print axioms fourthPowerWeight_axPos
#print axioms fourthPowerWeight_coarse_sum
#print axioms fourthPowerWeight_not_axNorm
#print axioms perspective_two_cases
#print axioms skewWeight_axPos
#print axioms skewWeight_axNul
#print axioms skewWeight_axNorm
#print axioms skewWeight_axGrain
#print axioms grain_does_not_imply_born_at_two
#print axioms maxExpectation_monotone
#print axioms maxExpectation_normalized_const
#print axioms maxExpectation_not_affine
#print axioms recordNeutral_refines
#print axioms recordNeutral_record_eq
#print axioms recordNeutral_payoff_eq
#print axioms recordNeutral_bornWeight_eq
#print axioms refinementNotInRecordAlgebra_holds
#print axioms born_insensitive_to_recordNeutral_refinement
#print axioms born_determined_by_accessible_record
#print axioms counting_sensitive_to_recordNeutral_refinement
#print axioms counting_underdetermined_by_accessible_record

-- Abstract lift (route qubit) and its EffectCalibration instantiation.
-- Fully qualified: several names collide with their concrete counterparts
-- already opened above (represents, canonicalWeight_axPos/axNorm,
-- RefinementInvariantLocal, refinementInvariantLocal_iff_pullback).
#print axioms EverettianProbability.Abstract.Act.agreeOn_refl
#print axioms EverettianProbability.Abstract.Act.agreeOn_symm
#print axioms EverettianProbability.Abstract.Act.agreeOn_trans
#print axioms EverettianProbability.Abstract.Act.indicator_self
#print axioms EverettianProbability.Abstract.Act.indicator_of_ne
#print axioms EverettianProbability.Abstract.Act.agreeOn_indicatorExpansion
#print axioms EverettianProbability.Abstract.V_congr_of_agreeOn
#print axioms EverettianProbability.Abstract.represents
#print axioms EverettianProbability.Abstract.weights_unique_on_cells
#print axioms EverettianProbability.Abstract.canonicalWeight_axPos
#print axioms EverettianProbability.Abstract.canonicalWeight_axNorm
#print axioms EverettianProbability.Abstract.refinementInvariantLocal_iff_pullback
#print axioms EverettianProbability.Abstract.canonicalWeight_grain
#print axioms EverettianProbability.Abstract.outcome_injective_effects
#print axioms EverettianProbability.Abstract.canonicalWeight_familyOfEstimationRule
#print axioms EverettianProbability.Abstract.effectExpectation_represents
#print axioms EverettianProbability.Abstract.effectWeight_eq_born_of_invariance
#print axioms EverettianProbability.Abstract.spinState_norm
#print axioms EverettianProbability.Abstract.spinLine_ne_bot
#print axioms EverettianProbability.Abstract.spinLine_ne_top
#print axioms EverettianProbability.Abstract.spinLine_weight
#print axioms EverettianProbability.Abstract.spinPerspective_effect_zero
#print axioms EverettianProbability.Abstract.F0_refinementInvariantLocal
#print axioms EverettianProbability.Abstract.F0_contextualNullSupport
#print axioms EverettianProbability.Abstract.spinUp_weight_eq_born
#print axioms EverettianProbability.Abstract.rationalExpectationFamily_effects_nonvacuous
#print axioms EverettianProbability.Abstract.refinementInvariantLocal_effects_nonvacuous
#print axioms EverettianProbability.Abstract.effectPerspective_outcomes_pos
#print axioms EverettianProbability.Abstract.pullbackAct_effects_apply
#print axioms EverettianProbability.Abstract.effectUniformCredence_coarse
#print axioms EverettianProbability.Abstract.effectUniformCredence_fine
#print axioms EverettianProbability.Abstract.effectUniform_not_refinementInvariantLocal

-- Static conditioning under refinement (P8): no record or temporal dynamics.
#print axioms EverettianProbability.Abstract.conditionalWeight_zero_of_not_in_fiber
#print axioms EverettianProbability.Abstract.conditionalWeight_nonneg
#print axioms EverettianProbability.Abstract.conditionalWeight_sum_eq_zero_or_one
#print axioms EverettianProbability.Abstract.conditionalWeight_normalized
#print axioms EverettianProbability.Abstract.conditionalExpectation_pullback_eq_of_weight_ne_zero
#print axioms EverettianProbability.Abstract.conditionalExpectation_total
#print axioms EverettianProbability.Abstract.conditionalWeight_trans_fiber
#print axioms EverettianProbability.Diachronic.uniformProjectiveExpectationFamily
#print axioms EverettianProbability.Diachronic.uniform_conditionalWeight_trans_fiber_lhs
#print axioms EverettianProbability.Diachronic.uniform_conditionalWeight_trans_fiber_rhs
#print axioms EverettianProbability.Diachronic.uniform_conditionalWeight_trans_fiber_fails

#print axioms EverettianProbability.Frequency.configurationBasis_mem_frequencySitesCell
#print axioms EverettianProbability.Frequency.frequencySitesCell_ortho
#print axioms EverettianProbability.Frequency.configurationBranch_norm
#print axioms EverettianProbability.Frequency.configurationBranch_ne_zero
#print axioms EverettianProbability.Frequency.configurationBranch_inner_eq_zero_of_ne
#print axioms EverettianProbability.Frequency.configurationBranch_mem_frequencyCell
#print axioms EverettianProbability.Frequency.frequencyCell_ortho
#print axioms EverettianProbability.Frequency.frequencySitesCell_iSup
#print axioms EverettianProbability.Frequency.frequencyCell_iSup
#print axioms EverettianProbability.Frequency.hammingWeight_le
#print axioms EverettianProbability.Frequency.frequencySitesCell_eq_bot_of_lt
#print axioms EverettianProbability.Frequency.frequencyCell_eq_bot_of_lt
#print axioms EverettianProbability.Frequency.frequencySitesCell_iSup_fin
#print axioms EverettianProbability.Frequency.frequencyCell_iSup_fin
#print axioms EverettianProbability.Frequency.hammingWeight_prefixConfiguration
#print axioms EverettianProbability.Frequency.frequencyCell_ne_bot
#print axioms EverettianProbability.Frequency.frequencyCell_injective
#print axioms EverettianProbability.Frequency.frequencyPerspective
#print axioms EverettianProbability.Frequency.frequencyCell_mem_frequencyPerspective
#print axioms EverettianProbability.Frequency.frequencyPerspective_cells_card

#print axioms EverettianProbability.Frequency.repetitionSitesVector_apply
#print axioms EverettianProbability.Frequency.sitesEquivR_repetitionVector
#print axioms EverettianProbability.Frequency.repetitionAmplitude_eq_of_hammingWeight_eq
#print axioms EverettianProbability.Frequency.repetitionSitesVector_eq_of_hammingWeight_eq
#print axioms EverettianProbability.Frequency.repetitionAmplitude_prefixConfiguration
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_nonneg
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_eq_of_hammingWeight_eq
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_prefixConfiguration
#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_sum
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_eq_norm_sq_powers
#print axioms EverettianProbability.Frequency.repetitionConfigurationWeight_prefix_eq_norm_sq_powers
#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_sum_norm_sq_powers

#print axioms EverettianProbability.Frequency.onesFinset_configurationOfOnes
#print axioms EverettianProbability.Frequency.configurationOfOnes_onesFinset
#print axioms EverettianProbability.Frequency.hammingWeightFiberEquiv
#print axioms EverettianProbability.Frequency.hammingWeight_fiber_card
#print axioms EverettianProbability.Frequency.configurationsOfWeight_card
#print axioms EverettianProbability.Frequency.hammingWeight_image_univ

#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_binomial_sum
#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_elementary_sum_pow
#print axioms EverettianProbability.Frequency.repetitionVector_norm_sq_eq_one
#print axioms EverettianProbability.Frequency.repetitionVector_norm_eq_one

#print axioms EverettianProbability.Frequency.frequencySitesCell_starProjection_configurationBasis
#print axioms EverettianProbability.Frequency.frequencyCell_starProjection_configurationBranch
#print axioms EverettianProbability.Frequency.projL_frequencyCell_configurationBranch
#print axioms EverettianProbability.Frequency.repetitionFrequencySitesComponent_apply
#print axioms EverettianProbability.Frequency.repetitionFrequencySitesComponent_eq_sum
#print axioms EverettianProbability.Frequency.repetitionSitesVector_eq_sum_configurationBasis
#print axioms EverettianProbability.Frequency.frequencySitesCell_starProjection_repetitionSitesVector
#print axioms EverettianProbability.Frequency.sitesEquivR_repetitionFrequencyComponent
#print axioms EverettianProbability.Frequency.projL_frequencyCell_repetitionVector
#print axioms EverettianProbability.Frequency.repetitionFrequencyComponent_mem_frequencyCell
#print axioms EverettianProbability.Frequency.repetitionFrequencySitesComponent_norm_sq_eq_sum
#print axioms EverettianProbability.Frequency.repetitionFrequencyComponent_norm_sq_eq_sum
#print axioms EverettianProbability.Frequency.projL_frequencyCell_repetitionVector_norm_sq_eq_sum
#print axioms EverettianProbability.Frequency.sum_repetitionConfigurationWeight_configurationsOfWeight
#print axioms EverettianProbability.Frequency.repetitionFrequencySitesComponent_norm_sq_eq_binomial
#print axioms EverettianProbability.Frequency.repetitionFrequencyComponent_norm_sq_eq_binomial
#print axioms EverettianProbability.Frequency.projL_frequencyCell_repetitionVector_norm_sq_eq_binomial
#print axioms EverettianProbability.Frequency.sum_projL_frequencyCell_repetitionVector_norm_sq_eq_elementary_sum_pow
#print axioms EverettianProbability.Frequency.sum_projL_frequencyCell_repetitionVector_norm_sq_eq_one
#print axioms EverettianProbability.Frequency.sum_frequencyPerspective_repetitionVector_norm_sq_eq_elementary_sum_pow
#print axioms EverettianProbability.Frequency.sum_frequencyPerspective_repetitionVector_norm_sq_eq_one
#print axioms EverettianProbability.Frequency.frequencyMass_eq_projectiveWeight
#print axioms EverettianProbability.Frequency.frequencyMass_nonneg
#print axioms EverettianProbability.Frequency.frequencyMass_eq_binomial
#print axioms EverettianProbability.Frequency.sum_frequencyMass_eq_elementary_sum_pow
#print axioms EverettianProbability.Frequency.sum_frequencyMass_eq_one
#print axioms EverettianProbability.Frequency.frequencyMass_isProbabilityFamily
#print axioms EverettianProbability.Frequency.sum_range_cast_mul_choose_mul_powers
#print axioms EverettianProbability.Frequency.frequencyCountFirstMoment_nonneg
#print axioms EverettianProbability.Frequency.frequencyCountFirstMoment_eq_general
#print axioms EverettianProbability.Frequency.frequencyCountFirstMoment_eq
#print axioms EverettianProbability.Frequency.sum_range_cast_fallingTwo_mul_choose_mul_powers
#print axioms EverettianProbability.Frequency.frequencyCountSecondFactorialMoment_nonneg
#print axioms EverettianProbability.Frequency.frequencyCountSecondFactorialMoment_eq_general
#print axioms EverettianProbability.Frequency.frequencyCountSecondFactorialMoment_eq
#print axioms EverettianProbability.Frequency.frequencyCountSecondMoment_eq_secondFactorialMoment_add_firstMoment
#print axioms EverettianProbability.Frequency.frequencyCountSecondMoment_nonneg
#print axioms EverettianProbability.Frequency.frequencyCountSecondMoment_eq_general
#print axioms EverettianProbability.Frequency.frequencyCountSecondMoment_eq
#print axioms EverettianProbability.Frequency.frequencyCountVariance_eq
#print axioms EverettianProbability.Frequency.frequencyCountVariance_nonneg
#print axioms EverettianProbability.Frequency.frequencyRelativeFirstMoment_eq_countFirstMoment_div
#print axioms EverettianProbability.Frequency.frequencyRelativeFirstMoment_eq
#print axioms EverettianProbability.Frequency.frequencyRelativeSecondMoment_eq_countSecondMoment_div_sq
#print axioms EverettianProbability.Frequency.frequencyRelativeVariance_eq_countVariance_div_sq
#print axioms EverettianProbability.Frequency.frequencyRelativeVariance_eq
#print axioms EverettianProbability.Frequency.frequencyRelativeVariance_nonneg
#print axioms EverettianProbability.Frequency.frequencyRelativeDeviationSecondMoment_nonneg
#print axioms EverettianProbability.Frequency.frequencyRelativeDeviationSecondMoment_eq
#print axioms EverettianProbability.Frequency.frequencyRelativeDeviationSecondMoment_eq_variance
#print axioms EverettianProbability.Frequency.frequencyAtypicalMass_nonneg
#print axioms EverettianProbability.Frequency.epsilon_sq_mul_frequencyAtypicalMass_le_deviationSecondMoment
#print axioms EverettianProbability.Frequency.frequencyAtypicalMass_le_deviationSecondMoment_div
#print axioms EverettianProbability.Frequency.frequencyAtypicalMass_le_chebyshev
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_nonneg
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_add_frequencyAtypicalMass_eq_totalMass
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_add_frequencyAtypicalMass_eq_one
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_eq_one_sub_frequencyAtypicalMass
#print axioms EverettianProbability.Frequency.frequencyTypicalMass_le_one
#print axioms EverettianProbability.Frequency.one_sub_chebyshev_le_frequencyTypicalMass
#print axioms EverettianProbability.Frequency.one_sub_delta_le_frequencyTypicalMass
#print axioms EverettianProbability.Frequency.chebyshevBound_le_delta_of_large_repetitions
#print axioms EverettianProbability.Frequency.frequencyAtypicalMass_le_delta_of_large_repetitions
#print axioms EverettianProbability.Frequency.one_sub_delta_le_frequencyTypicalMass_of_large_repetitions
#print axioms EverettianProbability.Frequency.exists_frequencyTypicality_threshold
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.evidence_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_evidence_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_nonneg
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_posteriorWeight_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.sum_posteriorWeight_eq_zero
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_mul_evidence
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_nonneg
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_eq_binomial
#print axioms EverettianProbability.Confirmation.sum_frequencyLikelihood_eq_one
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_evidence_eq
#print axioms EverettianProbability.Confirmation.sum_frequencyConfirmationModel_evidence_eq_one
#print axioms EverettianProbability.Confirmation.sum_frequencyConfirmationModel_posteriorWeight_eq_one
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_cross_mul
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_div_posteriorWeight_eq
#print axioms EverettianProbability.Confirmation.frequencyCellKernel_nonneg
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_eq_choose_mul_kernel
#print axioms EverettianProbability.Confirmation.frequencyLikelihood_div_eq_kernel_div
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_posteriorWeight_div_eq
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_lt_iff_jointWeight_lt
#print axioms EverettianProbability.Confirmation.FiniteBayesModel.posteriorWeight_eq_iff_jointWeight_eq
#print axioms EverettianProbability.Confirmation.frequencyBayesFactor_nonneg
#print axioms EverettianProbability.Confirmation.one_lt_frequencyBayesFactor_iff
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_posteriorOdds_eq_priorOdds_mul_bayesFactor
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_posteriorOdds_eq_bayesFactor_of_equal_prior
#print axioms EverettianProbability.Confirmation.frequencyConfirmationModel_posteriorWeight_lt_iff_kernel_lt_of_equal_prior
#print axioms EverettianProbability.Confirmation.rationalWitnessPrior_nonneg
#print axioms EverettianProbability.Confirmation.sum_rationalWitnessPrior_eq_one
#print axioms EverettianProbability.Confirmation.rationalWitnessAmplitudes_normalized
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_kernel_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_kernel_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_likelihood_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_likelihood_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_evidence_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessLow_posteriorWeight_eq
#print axioms EverettianProbability.Confirmation.rationalWitnessHigh_posteriorWeight_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_bayesFactor_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_posteriorOdds_eq
#print axioms EverettianProbability.Confirmation.rationalWitness_lowPosterior_lt_highPosterior

end EverettianProbability.Audit
